### ISSUE TITLE
What do you think of omniquant?

### ISSUE THREAD

**Issue by Ph0rk0z** [turboderp/exllamav2#1]
https://arxiv.org/abs/2308.13137

Is it comparable to the new version? This guy jammed falcon into 65G with decent PPL.

Uses the AutoGPTQ kernel so it must be similar. Maybe something can be plifered from it.

https://github.com/OpenGVLab/OmniQuant

**Comment by turboderp** [comment]
I've been way too preoccupied to look at it. But it does look interesting. I'm going to be checking it out eventually, for sure.
