### ISSUE TITLE
calling lora.unload() gives key error

### ISSUE THREAD

**Issue by Ph0rk0z** [turboderp/exllamav2#100]
I found loras still stuck in memory after being set to none. So I called the .unload() method.

I get a key error at : del v.lora_a_tensors[self]

Is there some proper way to unload them? I only tested with 70b so far. Otherwise lora stops being used when changed to none but stays in memory. Loading a subsequent lora takes additional vram.

**Comment by turboderp** [comment]
Each LoRA is attached to the model when loaded. You switch it on and off by passing it as an argument to forward(), but the reference still exists in the model regardless. The unload() method is supposed to detach it from the model, but it sounds like there's a bug. I will investigate.

**Comment by turboderp** [comment]
Should be fixed now.

**Comment by Ph0rk0z** [comment]
Ok I'll give it a try. Hopefully it frees the memory. I think after 3 or 4 70b loras I would go OOM unless I reloaded the model.

**Comment by Ph0rk0z** [comment]
Thanks, now it frees on next gen when unloaded.
