### ISSUE TITLE
Endless flood of 'rfm max: x.xx bpw x.xx' on quant

### ISSUE THREAD

**Issue by discordianbelle** [turboderp/exllamav2#101]
I've quantized 13B models locally on this machine (12 GB 3060, 32GB DDR5) without problem in the same env. I was able to run the measurement with '-ml 3072 -gr 100' entirely in VRAM. However, when it reached the quant step, it began flooding me with feedback as seen below, even with different variables (other than the model). Always a rising 'rfn max' and a bpw that freezes at 2.17438. I woke up this morning and the 'rfn max' was over 11k! Bits were still 2.17438.

Any advice?

*****

(exllama) blah@blah-blah:~/exllamav2$ python convert.py -i ./models/U-Amethyst-20B -o ./quantsUA -c ./parquet/pippa_alpaca.parquet -m ./measureUA/measurement.json -gr 100 -ss 4096 -l 3073 -ml 3073 -b 2 -nr

 !! Warning: calibration rows > 2048 tokens may result in excessive VRAM use
 -- Beginning new job
 !! Warning: Output directory is not empty: /home/raven/exllamav2/quantsUA
 !! Cleaning output directory: /home/raven/exllamav2/quantsUA
 -- Input: /home/raven/exllamav2/models/U-Amethyst-20B
 -- Output: /home/raven/exllamav2/quantsUA
 -- Calibration dataset: /home/raven/exllamav2/parquet/pippa_alpaca.parquet, 100 / 16 (100) rows, 3073 tokens per sample
 -- Target bits per weight: 2.0 (decoder), 6 (head)
 -- Max shard size: 4096.0 MB
 -- Reusing measurement: ./measureUA/measurement.json
 -- Optimizing...
 -- rfn max: 0.11478  bpw: 2.85208
 -- rfn max: 0.17222  bpw: 2.52931
 -- rfn max: 0.20099  bpw: 2.28973
 -- rfn max: 0.21542  bpw: 2.20746
 -- rfn max: 0.22269  bpw: 2.18370
 -- rfn max: 0.22637  bpw: 2.17685
 -- rfn max: 0.22826  bpw: 2.17538
 -- rfn max: 0.22926  bpw: 2.17512
 -- rfn max: 0.22981  bpw: 2.17438
 -- rfn max: 0.23013  bpw: 2.17438
 -- rfn max: 0.23034  bpw: 2.17438
 -- rfn max: 0.23050  bpw: 2.17438
 -- rfn max: 0.23063  bpw: 2.17438
 -- rfn max: 0.23074  bpw: 2.17438
 -- rfn max: 0.23085  bpw: 2.17438
 -- rfn max: 0.23095  bpw: 2.17438...

*****

(exllama) blah@blah-blah:~/exllamav2$ python convert.py -i ./models/U-Amethyst-20B -o ./quantsUA -c ./parquet/pippa_alpaca.parquet -m ./measureUA/measurement.json -b 2 -nr
 
 -- Beginning new job
 !! Warning: Output directory is not empty: /home/raven/exllamav2/quantsUA
 !! Cleaning output directory: /home/raven/exllamav2/quantsUA
 -- Input: /home/raven/exllamav2/models/U-Amethyst-20B
 -- Output: /home/raven/exllamav2/quantsUA
 -- Calibration dataset: /home/raven/exllamav2/parquet/pippa_alpaca.parquet, 100 / 16 (0) rows, 2048 tokens per sample
 -- Target bits per weight: 2.0 (decoder), 6 (head)
 -- Max shard size: 8192 MB
 -- Reusing measurement: ./measureUA/measurement.json
 -- Optimizing...
 -- rfn max: 0.11478  bpw: 2.85208
 -- rfn max: 0.17222  bpw: 2.52931
 -- rfn max: 0.20099  bpw: 2.28973
 -- rfn max: 0.21542  bpw: 2.20746
 -- rfn max: 0.22269  bpw: 2.18370
 -- rfn max: 0.22637  bpw: 2.17685
 -- rfn max: 0.22826  bpw: 2.17538
 -- rfn max: 0.22926  bpw: 2.17512
 -- rfn max: 0.22981  bpw: 2.17438
 -- rfn max: 0.23013  bpw: 2.17438
 -- rfn max: 0.23034  bpw: 2.17438
 -- rfn max: 0.23050  bpw: 2.17438
 -- rfn max: 0.23063  bpw: 2.17438
 -- rfn max: 0.23074  bpw: 2.17438
 -- rfn max: 0.23085  bpw: 2.17438...

*****

(exllama) blah@blah-blah:~/exllamav2$ python convert.py -i ./models/U-Amethyst-20B -o ./quantsUA -c ./parquet/wizard.parquet -m ./measureUA/measurement.json -b 2 -nr
 
 -- Beginning new job
 !! Warning: Output directory is not empty: /home/raven/exllamav2/quantsUA
 !! Cleaning output directory: /home/raven/exllamav2/quantsUA
 -- Input: /home/raven/exllamav2/models/U-Amethyst-20B
 -- Output: /home/raven/exllamav2/quantsUA
 -- Calibration dataset: /home/raven/exllamav2/parquet/wizard.parquet, 100 / 16 (0) rows, 2048 tokens per sample
 -- Target bits per weight: 2.0 (decoder), 6 (head)
 -- Max shard size: 8192 MB
 -- Reusing measurement: ./measureUA/measurement.json
 -- Optimizing...
 -- rfn max: 0.11478  bpw: 2.85208
 -- rfn max: 0.17222  bpw: 2.52931
 -- rfn max: 0.20099  bpw: 2.28973
 -- rfn max: 0.21542  bpw: 2.20746
 -- rfn max: 0.22269  bpw: 2.18370
 -- rfn max: 0.22637  bpw: 2.17685
 -- rfn max: 0.22826  bpw: 2.17538
 -- rfn max: 0.22926  bpw: 2.17512
 -- rfn max: 0.22981  bpw: 2.17438
 -- rfn max: 0.23013  bpw: 2.17438
 -- rfn max: 0.23034  bpw: 2.17438
 -- rfn max: 0.23050  bpw: 2.17438
 -- rfn max: 0.23063  bpw: 2.17438
 -- rfn max: 0.23074  bpw: 2.17438...

**Comment by turboderp** [comment]
The minimum bitrate supported is slightly above 2 (the precise value varies from model to model). But what's happening there is that it's endlessly trying to find a combination of quant parameters that give an average of 2.00 bits per weight, and when it doesn't have any smaller options to switch to it just gets stuck on the minimum.

I'm still working on options it would need to go lower, i.e. binary layers, low-rank approximations and such. As it is, though, the best you can get for that model would be about 2.18 bits per weight.

**Comment by discordianbelle** [comment]
Oh my gosh that's so obvious... thank you so much!

**Comment by turboderp** [comment]
Well, to be fair it should probably detect that it's stuck in a loop and either fall back on the achievable minimum or exit with an error message. I'll make a note of it.
