### ISSUE TITLE
Sliding Attention Window

### ISSUE THREAD

**Issue by anujnayyar1** [turboderp/exllamav2#103]
Dear @turboderp,

Just wondering if you have been able to implement the sliding attention window for mistralai/Mistral-7B-v0.1 and its derivatives, 

It would be awesome to be able to use this model up to its full context window, with the speed of exllama!!

All the very best and thank you so much for your continued amazing contributions to the community!!

**Comment by turboderp** [comment]
I've considered various ways of implementing it, and the problem isn't actually the SWA itself but rather creating an API for it that doesn't break everything else.

Keep in mind, all it does (unless I'm still completely failing to understand the paper) is truncate the cache, as opposed to truncating and reevaluating the context. You don't actually get a 32k context size or 128k or whatever they advertise. If you have a 4k sliding window, any tokens more than 4k positions in the past are still forgotten and can no longer be attended to. They may still be vaguely reflected in the keys and values produced before that past was forgotten, but the actual keys are no longer present and there's only so much information that can be conveyed without them, especially with the shorter GQA keys/values of Mistral.

So it's very questionable how valuable SWA is for context size, and after all Mistral works well past the 4k window size when used as a regular Llama model (good for at least 7k in my tests).

As for speed, it is faster to truncate (or better yet, roll) the cache than to truncate the context, but it's not a *huge* difference in the end. You typically wouldn't truncate the context for every token added, but maybe for every 200 tokens or so. At that point, you're just resetting the cache and forwarding the truncated context as a prompt, which will process at some 14,000 tokens/second on a 4090. So it's not much of a stutter you get, and it's not all that often.

One big problem with truncating/rolling the cache is that you lose the system prompt, character cards and whatever else you stuck at the beginning of the context. If you settle for the "regular approach" it's trivial to retain those parts of the context when truncating (both the CLI chat example in ExLlamaV2 and the web UI in V1 do this).

I've yet to work out if there's some sort of compromise that would mark part of the cache to retain as the rest of it rolls. But either way it's going to complicate the interface, as there isn't really a way to do it transparently, I don't think.

So yes, I do plan to do *something* with it, but I'm not sure what form it will take, and I'd advise everyone not to make too many assumptions about the benefits of SWA.

**Comment by Tostino** [comment]
@turboderp So the issue with the system prompt / character card sliding out of context is solved by locking a portion of the KV cache (first  N tokens), and then truncate the sliding window that begins after that locked portion. 

With llamacpp you just use --keep [token count of system prompt]

**Comment by Qubitium** [comment]
@Tostino  But that means the sliding context is a disjointed/non-continuous franken merge of header + footer with middle cutoff. Not sure how this would degrade output. At least the current sliding window is a mostly continuous/coherent message. Have you tried this --keep method and gotten acceptable output?

**Comment by Tostino** [comment]
I think you misunderstood what I was trying to describe. I have tried it by setting --keep in llamacpp and it successfully continued generation after truncating the sliding window portion. 


Without recompiling, it discards half of the sliding window portion of the kv cache, but that is easy to change to discard whole conversation turns at a time instead.

I don't quite understand what you mean by disjointed header, middle, and footer. You just have a fixed "header" section, and you add to the end of your sliding window until it is full, and then it starts discarding the tokens after your header section at the beginning of your sliding window.

So I don't quite get how it could be disjointed.

**Comment by Qubitium** [comment]
@Tostino  I think we are talking about the same thing. Let me rewrite my end to be more clear. A -> B ->C . If A is fixed header in --keep, and B is the extra part that is > sliding window, you are asking model to generate D with A -> C.  Generation of D (next part) having attentions to A and C with B chopped off. My worry is that the cutting the  linear generated B that precedes C may cause issues. Could be wrong on this as you have said it is working correctly in your case.

**Comment by Tostino** [comment]
Ah, yeah it will only work with tasks that will not require referring back to information at the start of B by the time we need to truncate it. E.g. I can stuff a document almost to the entire context length of the LLM, and ask for a summary where the generated summary would overflow the available context window. After we have summarized the first paragraph, we don't really care if it is truncated in my experience. Or at least it hasn't mattered for me when I was testing on some of my tasks that would possibly work with this.

**Comment by turboderp** [comment]
Closing this as stale. Rolling context may be addressed in the future with continuous batching/paged attn at some point.
