### ISSUE TITLE
Early perplexity broken on higher quants. Gibberish outputs. 

### ISSUE THREAD

**Issue by 11415142513152119** [turboderp/exllamav2#107]
When quantizing at 9bpw, models exhibit completely skyrocketed perplexity leading to gibberish outputs when generating with very low filled context (around under 100 tokens). It seems to affect some models, and lowering the -b to 8 fixes it. It's not a problem with already filled context, but it makes it impossible to use short instruct prompts on some models.
I'm not sure if it's something related to calibration/measurements but it happens.
EDIT: Funnily enough, one of my test quants was so on edge with this that I sometimes got the gibberish outputs when reclicking token probabilities on the same input. Exllama non-determinism must have been enough to somehow "trigger" it sometimes.

**Comment by turboderp** [comment]
Well, I haven't tested it extensively for a case like that. It's possible the quantizer gets confused since it can't actually produce a 9-bit model. It should just arrive at the max bitrate and that should be at least as good as 8.0 bits. But I'll look into it.

**Comment by 11415142513152119** [comment]
Generally that the one script that maxxed out all layers to 8.13 was producing issues like that even more makes me think some kind of overflowing happens if too many layers are maxxed out maybe? It'd explain why using -b 9 would fix it in some models that broke with the script and why using -b 8 fixes it in those models that still break with -b 9.

**Comment by krzysiekpodk** [comment]
HumanEval results for Phind v2 quants, something goes bad above 5bit, I used Evol Instruct for calibration:

4.25bit
{'pass@1': 0.7073170731707317}
Base + Extra
{'pass@1': 0.6463414634146342}

5bit
{'pass@1': 0.7073170731707317}
Base + Extra
{'pass@1': 0.6707317073170732}

6bit
{'pass@1': 0.7012195121951219}
Base + Extra
{'pass@1': 0.6463414634146342}

8bit
{'pass@1': 0.2682926829268293}
Base + Extra
{'pass@1': 0.25609756097560976}
 -- Calibration perplexity (quant): 1.9978 (more or less the same a little lower than other quants - nothing extraordinary here)

**Comment by 11415142513152119** [comment]
> Well, I haven't tested it extensively for a case like that. It's possible the quantizer gets confused since it can't actually produce a 9-bit model. It should just arrive at the max bitrate and that should be at least as good as 8.0 bits. But I'll look into it.

Anything new regarding this?

**Comment by turboderp** [comment]
(this should be okay now)
