### ISSUE TITLE
Weird performance

### ISSUE THREAD

**Issue by jianyuheng** [turboderp/exllamav2#109]
I found that the performance of llama-30b-4bpw(33.43 tokens/s) is very close to llama-13b-4bpw(35.41 tokens/s).
Test environment: A100-40G.

**Comment by CyberTimon** [comment]
What CPU do you have? Maybe on the 13b there is a cpu bottleneck and when loading the 30b you are in the gpu bottleneck?

**Comment by turboderp** [comment]
Closing as stale.
