### ISSUE TITLE
Production of quantitative datasets and expansion of models

### ISSUE THREAD

**Issue by venxzw** [turboderp/exllamav2#113]
I would like to ask if the quantified dataset should be in a wiki format or similar to training data. If you want to create it yourself, what format should you use; Secondly, can this framework quantify other models?I would like to ask if the quantified dataset should be in a wiki format or similar to training data. If you want to create it yourself, what format should you use; Secondly, can this framework quantify other models?

**Comment by turboderp** [comment]
The converter interprets the input Parquet file as a blob of text (by concatenating all the text fields it contains) which is then chunked up into rows of equal length as defined by the command-line arguments.

The quantizer then uses this data as the input to one large forward pass through the model, recording the intermediate hidden state before and after every linear layer that is to be quantized. These states are used as a reference to adjust the quantization grid and to perform the GPTQ error compensation. 

This means the model becomes "specialized", to some degree depending on how aggressive the bitrate is, in reproducing the internal states produced by the calibration data. It will still work with other data, it will just work more precisely when dealing with inputs similar to what it was calibrated on. 

I don't think there's a perfect consensus on what the calibration dataset should look like, but you most likely want the calibration data to resemble data that you intend to feed the quantized model later on.

**Comment by venxzw** [comment]
> The converter interprets the input Parquet file as a blob of text (by concatenating all the text fields it contains) which is then chunked up into rows of equal length as defined by the command-line arguments.
> 
> The quantizer then uses this data as the input to one large forward pass through the model, recording the intermediate hidden state before and after every linear layer that is to be quantized. These states are used as a reference to adjust the quantization grid and to perform the GPTQ error compensation.
> 
> This means the model becomes "specialized", to some degree depending on how aggressive the bitrate is, in reproducing the internal states produced by the calibration data. It will still work with other data, it will just work more precisely when dealing with inputs similar to what it was calibrated on.
> 
> I don't think there's a perfect consensus on what the calibration dataset should look like, but you most likely want the calibration data to resemble data that you intend to feed the quantized model later on.
> 
> As for other models, the framework is written for Llama models specifically. That includes Llama, Llama-2, CodeLlama and Mistral, as well as any models that derive from them. I may add support for more architectures over time, especially if something ends up really standing out or gaining a lot of adoption. But I also have limited time, and I'm not looking to (and couldn't hope to) create and maintain an alternative to HF Transformers.

Thank you for your contribution to the quantification work. I have tried the quantification of llama2-13b and the acceleration effect is very obvious. I look forward to supporting more models in this project. I hope that in terms of quantifying datasets, we can achieve a format similar to that in autogptq. Thank you again for your contribution.
