### ISSUE TITLE
aws gpu compatibility

### ISSUE THREAD

**Issue by gtkafka** [turboderp/exllamav2#12]
does exllama run on any of the GPUs offered on aws:  V100, A100, Tesla M60, T4, or A10G? I ran autogpt, but had to disable exllama for it to work.
Thanks!

**Comment by turboderp** [comment]
I've tested it on A100 at least, but I'm not sure about the others. There's no reason it should work any differently there than any other CUDA device (if maybe not optimized for their respective performance profiles), but I can't speak to the specifics of how it's been included in AutoGPTQ.
