### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by bazinga-zero** [turboderp/exllamav2#120]
assert os.path.exists(self.model_config), "Can't find " + self.model_config
AssertionError: Can't find /home/llama/llama-2-70b-chat/config.json

I download the llama2-70B model from the llama github, but there is no config.json in this model folder. How can I get config.json?

**Comment by Ph0rk0z** [comment]
pull it from another llama-2-70b

**Comment by turboderp** [comment]
You need the HF version of the model, in FP16 format. [Here's one example](https://huggingface.co/TheBloke/Llama-2-70B-fp16). You can then either convert that to EXL2 format or run it directly, but running it directly requires about 148 GB of VRAM (e.g. two A100-80GB GPUs).

The implementation will also work with 4-bit GPTQ models, and there are many such conversions of Llama2-70B on Hugging Face as well. I've uploaded [a number of EXL2 models](https://huggingface.co/turboderp) at various bitrates, including Llama2-70B and Llama2-70B-chat, down to sub-3-bit conversions that will run on a single 24 GB GPU.
