### ISSUE TITLE
Please add a web server

### ISSUE THREAD

**Issue by ehartford** [turboderp/exllamav2#122]
I would like to request an API server similar to what llama-cpp-python has implemented.

https://github.com/abetlen/llama-cpp-python#web-server

https://github.com/abetlen/llama-cpp-python/blob/main/llama_cpp/server/app.py

I would like it to expose endpoints compatible with 
OpenAI
```
POST /v1/completions
POST /v1/chat/completions
```
and also TGI / OpenLLM / vllm format
```
POST /generate
POST /generate_stream
```

The /v1/chat/completions should use the huggingface tokenizer to convert the messages to prompt:

```
prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
```

the stream argument should be respected

Thank you!

**Comment by sundaraa-deshaw** [comment]
Hi,

Similar to the we_server.py example that allows to open a web socket server on top of a model, can we add support for a API server (HTTP?) that can expose an underlying model via exllamav2 engine?

Arun

**Comment by turboderp** [comment]
There is now [tabbyAPI](https://github.com/theroyallab/tabbyAPI) which provides an OpenAI-style API interface to ExLlamaV2. It's still very new, but worth checking out I think.

**Comment by ehartford** [comment]
ok but, I think you should consider merging tabby into this repo, making it a feature of exllamav2

**Comment by jbohnslav** [comment]
TabbyAPI has an AGPL license, which is much more restrictive than this repo's MIT license.
