### ISSUE TITLE
Install without GPU

### ISSUE THREAD

**Issue by kopyl** [turboderp/exllamav2#126]
When i build a Docker image on a machine with no GPU, after executing this `python setup.py install --user` i get a huge error:

https://pastebin.com/bCBcTszR

How can i install the app without GPU?

**Comment by kopyl** [comment]
Fixed by
1. Running `RUN apt update && apt install -y libpython3.10-dev` before `RUN python setup.py install --user` 
2. Replacing `RUN python setup.py install --user` with `RUN TORCH_CUDA_ARCH_LIST=Turing python setup.py install --user` (added `TORCH_CUDA_ARCH_LIST=Turing`)

(2nd thing was needed to fix another error)

**Comment by ashleykleynhans** [comment]
Thanks @kopyl , this solved the issue for me too.
