### ISSUE TITLE
Recovering Embedding from the model

### ISSUE THREAD

**Issue by ParisNeo** [turboderp/exllamav2#127]
Hi. I wonder if there is a method to use the model to generate embeddings
If it is possible to get the output of the encoder (the latent space), I can use that for data vectorization.
Is there any plans to have such functionality?

**Comment by ParisNeo** [comment]
I was thinking of just the output of the encoder part

**Comment by turboderp** [comment]
If you mean straight out of the embedding layer, you can call it directly:

```python
input_ids = tokenizer.encode("Hello world")  # shape (bsz, seq_len)

embedding_layer = model.modules_dict["model.embed_tokens"]
embeddings = embedding_layer.forward(input_ids)  # shape (bsz, seq_len, hidden_size)
```
