### ISSUE TITLE
Flash-decoding is supported?

### ISSUE THREAD

**Issue by ChuanhongLi** [turboderp/exllamav2#128]
Hi, is flash-decoding supported in exllama(v1 and v2) ?

**Comment by turboderp** [comment]
Honestly I don't know. I just haven't had time to look into how it's implemented in the latest versions of flash-attn. It might be used by default, or it might not be relevant at all.

EXLlamaV2 (and V1 for that matter, in its own obsolete way) just call `flash-attn-func` and then the library does the rest. Maybe that involves flash decoding? Who can say. There are some other things on the agenda first, but I'll get to the bottom of it eventually.
