### ISSUE TITLE
使用covert.py报错了

### ISSUE THREAD

**Issue by sunbeibei-hub** [turboderp/exllamav2#130]
(bei_exllamav2) [root@iZj6c0kxm1epm4sqdrtcsgZ exllamav2]# python convert.py \
>     -nr \
>     -i /root/bei/Models/openbuddy-llama2-70b-v10.1-bf16 \
>     -o /root/bei/Models/openbuddy-llama2-70b-v10.1-bf16-exllamav2 \
>     -cf /root/bei/Models/openbuddy-llama2-70b-v10.1-bf16-exllamav2 \
>     -c /root/bei/exllamav2/wikitext-103-v1/0000.parquet \
>     -hb 8 \
>     -b 8.0

 -- Beginning new job
 !! Warning: Output directory is not empty: /root/bei/Models/openbuddy-llama2-70b-v10.1-bf16-exllamav2
 !! Cleaning output directory: /root/bei/Models/openbuddy-llama2-70b-v10.1-bf16-exllamav2
 -- Input: /root/bei/Models/openbuddy-llama2-70b-v10.1-bf16
 -- Output: /root/bei/Models/openbuddy-llama2-70b-v10.1-bf16-exllamav2
 -- Calibration dataset: /root/bei/exllamav2/wikitext-103-v1/0000.parquet, 100 / 16 (0) rows, 2048 tokens per sample
 -- Target bits per weight: 8.0 (decoder), 8 (head)
 -- Max shard size: 8192 MB
 -- Full model will be compiled to: /root/bei/Models/openbuddy-llama2-70b-v10.1-bf16-exllamav2
 !! Warning: Output path /root/bei/Models/openbuddy-llama2-70b-v10.1-bf16-exllamav2 exists but is not empty
 -- Tokenizing samples (measurement)...
Traceback (most recent call last):
  File "/root/bei/exllamav2/convert.py", line 236, in <module>
    tokenize(job, save_job, tokenizer, measure = True)
  File "/root/bei/exllamav2/conversion/tokenize.py", line 44, in tokenize
    cal_tokens = get_tokens(rows, length, cal_ds, tokenizer)
  File "/root/bei/exllamav2/conversion/tokenize.py", line 11, in get_tokens
    df = pandas.read_parquet(filename, engine = "fastparquet")
  File "/root/miniconda3/envs/bei_exllamav2/lib/python3.9/site-packages/pandas/io/parquet.py", line 670, in read_parquet
    return impl.read(
  File "/root/miniconda3/envs/bei_exllamav2/lib/python3.9/site-packages/pandas/io/parquet.py", line 400, in read
    parquet_file = self.api.ParquetFile(path, **parquet_kwargs)
  File "/root/miniconda3/envs/bei_exllamav2/lib/python3.9/site-packages/fastparquet/api.py", line 136, in __init__
    self._parse_header(fn, verify)
  File "/root/miniconda3/envs/bei_exllamav2/lib/python3.9/site-packages/fastparquet/api.py", line 216, in _parse_header
    f.seek(-(head_size + 8), 2)
OSError: [Errno 22] Invalid argument

**Comment by sunbeibei-hub** [comment]
(bei_exllamav2) [root@iZj6c0kxm1epm4sqdrtcsgZ exllamav2]# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0



![image](https://github.com/turboderp/exllamav2/assets/89978551/09148115-086d-464c-a3c8-f30d46f72e37)

**Comment by turboderp** [comment]
That's a new one. The error is occurring in fastparquet, apparently when trying to read the header of `wikitext-103-v1/0000.parquet`. Is there a problem with that file, perhaps? Maybe permissions related?

On a side note, you probably shouldn't use the same directory for the `-o` and `-cf` parameters. I'm not sure if it would work, but `-o` is the work directory where temporary files are stored, and they're copied to the other folder once the model is quantized. It might mess up.

**Comment by sunbeibei-hub** [comment]
Ok, I'll try
