### ISSUE TITLE
System crash while loading Dolphin-2.1-70B-4bit-128g-GPTQ in webui

### ISSUE THREAD

**Issue by surflip** [turboderp/exllamav2#133]
I'm using Exllamav2 to load 70b with GPTQ group size and when the load completes in WebUI, the system crashes. if add --auto-devices will crashes immediately when load.

1. There is no problem with exl2 files and ordinary 4bit GPTQ
2. This model (Dolphin-2.1-70B-4bit-128g-GPTQ) can be loaded using exllamav1
3. It appears to be a relevant system record
   python.exe 
   3.11.5150.1013 
   64ff15d0 
   c10.dll 
   0.0.0.0 
   650da48f 
   c0000005 
   0000000000055474 
   4348 
   01da0889fcb4f4f1 
   F:\text-generation-webui-1026\text-generation-webui-main\installer_files\env\python.exe 
   F:\text-generation-webui-1026\text-generation-webui-main\installer_files\env\Lib\site-packages\torch\lib\c10.dll 
   46ba660a-8bd0-4fbb-85cc-4b99bc87c08b

**Comment by turboderp** [comment]
This seems to have slipped under the radar. Please open again if the issue manifests with more recent versions.
