### ISSUE TITLE
Bad performance on 4090

### ISSUE THREAD

**Issue by snoonoo** [turboderp/exllamav2#134]
Running test_inference.py per instruction I'm getting 0.81 t/s vs the 35 t/s per README using ``Llama2-70B-chat-exl2 2.5 bpw``.

My setup is:
```
Torch version: 2.1.0
CUDA available: True
CUDA version: 12.1
Number of CUDA devices: 1
Current CUDA device: 0
CUDA device name: NVIDIA GeForce RTX 4090
```

Did I miss any setup or config?

**Comment by turboderp** [comment]
What's your NVIDIA driver version?

**Comment by snoonoo** [comment]
> What's your NVIDIA driver version?

I'm on version: 545.92 release date: 10/26/2023

**Comment by snoonoo** [comment]
I've also tried downgrading the driver to 531.79, result:
` -- Response generated in 127.01 seconds, 128 tokens, 1.01 tokens/second (includes prompt eval.)`

**Comment by Qubitium** [comment]
@snoonoo  How much system ram do you have? Check your ram swap/usage. Inference is ultra latency sensitive so swap will result in performance nose dive.

**Comment by snoonoo** [comment]
Dug through other issues, found my solution here https://github.com/turboderp/exllamav2/issues/47#issuecomment-1727723455

Using `-l 2048` gave me 32.26 tokens/second
