### ISSUE TITLE
Suggestion: Implement MinP

### ISSUE THREAD

**Issue by Chanka0** [turboderp/exllamav2#140]
This is an alternative sampling method to Top P and Top K. I've personally tested it with KoboldCPP and had really good results from it, even on higher temperatures.

There was a [llama.cpp implementation](https://github.com/ggerganov/llama.cpp/pull/3841) recently merged which details in depth why this is better and the [KoboldCPP implementation](https://github.com/kalomaze/koboldcpp/tree/minP).

**Comment by Ph0rk0z** [comment]
It's there already.. i've been using the dynamic temperature: https://github.com/kalomaze/text-generation-webui/releases

**Comment by noneabove1182** [comment]
that's his fork of text-generation-webui, it would be pretty nifty if it was directly implemented in exllamav2, i agree with Chanka0

**Comment by Ph0rk0z** [comment]
Read the code. It replaces sampler.py with both minp and dynamic temperature. It works with anything. The releases are what you're looking for, the committed code in the repo itself is for something else.

**Comment by r7vz9h3** [comment]
I think this issue should be closed? https://github.com/turboderp/exllamav2/commit/0d436d7ac35c402698c37bb73e534f8e5aad839a
