### ISSUE TITLE
The turboderp 70B quants on HuggingFace are broken

### ISSUE THREAD

**Issue by 11415142513152119** [turboderp/exllamav2#142]
The 2.4 and 2.5 quants of turboderp/Llama2-70B-exl2 are completely broken, outputting garbage tokens. Not sure about other sizes. 
I saw the same tokens on some finetune quants that size too, like LoneStriker/airoboros-l2-70b-3.1-2.4bpw-h6-exl2

![1](https://github.com/turboderp/exllamav2/assets/146097564/6ca15b7e-3a4a-49fa-9bcb-738e6508702b)

**Comment by 11415142513152119** [comment]
This works https://github.com/oobabooga/text-generation-webui/discussions/4188
Just keep in mind that on oobabooga it does not apply the option without do_sample.

**Comment by turboderp** [comment]
I've seen the "Cord" token pop up a lot. There's something special about that token and I haven't really figured out what, but yeah, it has to do with getting the prompt format right. Some models can't handle BOS tokens, others can't do without them.
