### ISSUE TITLE
Implement Efficient Streaming Language Models with Attention Sinks

### ISSUE THREAD

**Issue by BigArty** [turboderp/exllamav2#145]
This paper introduces the way to make inference of a LLM for a big context sizes. The main idea is that we can just shift cached results to the left with fixed attention window, but for significant increase of accuracy we need to save first several tokens (1-4) of the sequence. In the paper it is shown that this way of inference is on par with sliding window with recomputation of cache, but without the recomputations. 
https://arxiv.org/abs/2309.17453

**Comment by turboderp** [comment]
See #103.
