### ISSUE TITLE
Support for 01-ai/Yi series of models?

### ISSUE THREAD

**Issue by anujnayyar1** [turboderp/exllamav2#150]
Hey @turboderp!
Any chance of support for the new 01-ai/Yi-34B-200K models?

I see there has been an attempt to make them easier to model with llama based repos:
https://huggingface.co/chargoddard/Yi-34B-Llama

Keep up the awesome work!!

**Comment by anujnayyar1** [comment]
Seen its supported already!!!

**Comment by turboderp** [comment]
Yep. You need to clone from the repo or wait for 0.0.8 release soon, because it didn't make it into 0.0.7. Or use some of the Llamafied versions.
