### ISSUE TITLE
Yi models generates some languages in an incorrect encoding

### ISSUE THREAD

**Issue by samuelazran** [turboderp/exllamav2#155]
For example, I prompt it to extract an entity from a text in Hebrew, and it produces: "���� ���"
It seems to work ok with language understanding of Hebrew but the decoding of the tokens when generating Hebrew seems buggy only when using Exllamav2 (the same prompt with the same model works perfect with Huggingface Transformers). 

What could be the issue? Could it be their custom tokenizer? 

I've tested it with the latest exllamav2 (from the commit with the Yi models support addition) with several models including "01-ai/Yi-34B-200K" and "LoneStriker/Yi-34B-200K-6.0bpw-h6-exl2" from Huggingface models.

Attaching here a screenshot.
<img width="1414" alt="Screenshot 2023-11-09 at 14 06 39" src="https://github.com/turboderp/exllamav2/assets/2499928/bfe616fa-5a12-4291-af98-d7af716e68af">

**Comment by turboderp** [comment]
Thank you for noticing. It was actually nothing to do with the tokenizer but rather the streaming decoder which wasn't catching 2-byte UTF8 characters. It should be fixed with the latest commit:

![image](https://github.com/turboderp/exllamav2/assets/11859846/6031b295-b913-4763-9172-c0c33b470b6a)
