### ISSUE TITLE
Tweak to multiple cache example

### ISSUE THREAD

**Issue by dvianisoho** [turboderp/exllamav2#157]
Believe line 116 should be  `for i in sorted(eos, reverse=True):` to cover the case where a multiple prompts finish at the same time and one closer to the front of the queue gets popped first.

**Comment by turboderp** [comment]
The eos list is already in reverse order for that reason:

```python
    eos = []
    ...
    for i in range(len(input_ids)):
        ...
            eos.insert(0, i)
```

**Comment by dvianisoho** [comment]
You are right.   For some reason when I implemented this I was appending to the list, not inserting at the beginning.
