### ISSUE TITLE
exllamav2 Installation Error : [Errno 20] Not a directory: 'hipconfig'.

### ISSUE THREAD

**Issue by watchstep** [turboderp/exllamav2#158]
I'm trying to install exllamav2  in a CUDA version 11.8 and Python (CP) version 3.8 environment. 
When I try to import exllamav2, I encounter an error: **NotADirectoryError: [Errno 20] Not a directory: 'hipconfig'**.
I would like to resolve this issue. I have attempted all three methods mentioned in the readme (git clone, whl installation, pip package installation), but the same error persists

![image](https://github.com/turboderp/exllamav2/assets/88659167/979d19fe-66f3-4c16-950d-2b8fa4a054c3)

**Comment by turboderp** [comment]
Are you on an AMD GPU?

**Comment by watchstep** [comment]
I run on an Nvidia GPU not AMD GPU.
![image](https://github.com/turboderp/exllamav2/assets/88659167/ef611a54-a399-4276-9b79-de74578e7d8d)

**Comment by turboderp** [comment]
Are you on Torch 1.14? I'm not sure that's going to work. All development has been done on 2.x, with 2.1.0 being the current minimum requirement.

**Comment by watchstep** [comment]
![image](https://github.com/turboderp/exllamav2/assets/88659167/e26a973b-99a7-4e91-846e-719b0c67842f)

The PyTorch version in the development environment is 2.0.1, within a virtual environment.

**Comment by turboderp** [comment]
This is an odd one, I must say. I've never used Nvidia GPU Cloud, so I'm not really sure where to start debugging that. Could you say a little more about the setup?

**Comment by watchstep** [comment]
After updating to **Python version 3.10** and **Pytorch version 2.0.1+cu118**, and installing exllamav2 using pip install, importing exllamav2 worked well.

Thank you for making this package.
