### ISSUE TITLE
Support Baichuan2? 

### ISSUE THREAD

**Issue by lx0126z** [turboderp/exllamav2#16]
Baichuan2 is a generative model similar to llama, I find the following two differences:
- 1. qkv merge as W_pack
- 2. rotary changes to alibi

 Is there a plan to support Baichuan2?
- link
https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat
https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat/blob/main/modeling_baichuan.py

**Comment by venxzw** [comment]
+1

**Comment by venxzw** [comment]
@lx0126z May I ask if you have tried to quantify on Baihuan1, or have you used this framework to quantify other models besides llama?
