### ISSUE TITLE
Support cfg sampler?

### ISSUE THREAD

**Issue by win10ogod** [turboderp/exllamav2#18]
Is there a plan to support cfg sampler?

**Comment by turboderp** [comment]
There is, but the way in which it's supported is sort of tied to how it's going to be used by the front-end. It requires a separate context to be evaluated in parallel, either by batching or by a separate generator instance, so it can't just be reduced to an argument passed to the sampler.

I'm not sure exactly what the best approach is in relation to TGW or whatever.
