### ISSUE TITLE
Any plans for Mac/Metal support?

### ISSUE THREAD

**Issue by aikitoria** [turboderp/exllamav2#184]
Hi, I've been using this library on a 4090 with great success (it provides absolutely best in class performance there).

I was considering getting a Mac with the M2 Ultra 128-192GB unified memory to run larger models, until I saw that this library is currently only implemented for CUDA and ROCM. Do you already have any plans to port it to Metal?

**Comment by turboderp** [comment]
There are currently still no plans to add Mac support, no. I don't own one and can't see myself getting one anytime soon. Feel free to take a stab at it though. :)

**Comment by ehartford** [comment]
what if I send you a mac? @turboderp

**Comment by ehartford** [comment]
it's kind of a big deal, almost all AI devs use macbooks
