### ISSUE TITLE
Support GPT2 tokenizer for CausalLM 72b

### ISSUE THREAD

**Issue by CyberTimon** [turboderp/exllamav2#196]
Hello! When trying to load CausalLM 72b with exllamav2 to quant or infer, you will get this error:

```
  File "/home/ubuntu/git/exllamav2/exllamav2/tokenizer.py", line 67, in __init__
    else: raise FileNotFoundError("No supported tokenizer found.")
FileNotFoundError: No supported tokenizer found.
```

But you can load the tokenizer vocab as a GPT2 tokenizer with AutoTokenizers. With the recent Deepseek tokenizer additon, I don't think it will be hard to support also this one - or am I wrong?

Kind regards,
Timon Käch

Ref: https://huggingface.co/CausalLM/72B-preview/discussions/2
CausalLM-72B: https://huggingface.co/CausalLM/72B-preview

**Comment by CyberTimon** [comment]
Sure, thanks for the answer. The model has a tokenizer_config.json file which looks like this:
```
{
  "add_prefix_space": false,
  "bos_token": "<|endoftext|>",
  "tokenizer_class": "GPT2Tokenizer",
  "clean_up_tokenization_spaces": true,
  "eos_token": "<|endoftext|>",
  "model_max_length": 1000000000000000019884624838656,
  "unk_token": "<|endoftext|>"
}
```

and a vocab.json, which is quite big and has following structure:

```
{
  "!": 0,
  "\"": 1,
  "#": 2,
  "$": 3,
  "%": 4,
  "&": 5,
  "'": 6,
  ...
```

+ a additional_tokens.json file. 

Does this look like something that can be loaded? Thank you 😄

**Comment by CyberTimon** [comment]
Does this error just happen because it only searches for tokenizer.json / .model? and after adding vocab.json it should work? I'm still downloading the model atm that's why I can't test it but I know this error will pop up as other people have it.

**Comment by turboderp** [comment]
It loads the tokenizer.model file using SentencePiece or tokenizer.json using Tokenizers. It's likely that Tokenizers can also work with a vocab.json file, maybe initializing from some of the information in tokenizer_config.json? Hard to say. It's not like any of this is really standardized.

**Comment by CyberTimon** [comment]
I will try it when it finished downloading. Also, check here if you want to see how the gpt2 tokenizer works: https://huggingface.co/gpt2/tree/main. CausalLM 72b has basically the same tokenizer config and vocab

**Comment by CyberTimon** [comment]
Closing as the model has other issues and has nothing todo with this repo
