### ISSUE TITLE
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'

### ISSUE THREAD

**Issue by Hashflower** [turboderp/exllamav2#21]
Running 
PyTorch version: 2.0.1+cu117
CUDA version: 11.7

But when executing the model im getting that error :
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'

The command : python examples/chat.py -m model.safetensors -p "Are you alive?"

**Comment by turboderp** [comment]
Did this get resolved?
