### ISSUE TITLE
CPU offloading

### ISSUE THREAD

**Issue by bibidentuhanoi** [turboderp/exllamav2#225]
Is there any way that I can offload the model to the CPU? My machine has limited resources (32 GB of RAM and 6 GB of VRAM). Thank you.

**Comment by turboderp** [comment]
There is no built-in way, no. If your NVIDIA driver supports system RAM swapping, that's a way to run larger models than you could otherwise fit in VRAM, but it's going to be horrendously slow. You may be better off running GGUF models in llama.cpp, offloading what you can onto the GPU but doing CPU inference for the rest.

**Comment by bibidentuhanoi** [comment]
Thank you. I have tried using llama.cpp, but the output from that model is pretty unsusable(even the q8_0) compared to the Exl2 model. Anyway, what an amazing project you have here.

**Comment by Originalimoc** [comment]
@turboderp 
How hard is to add CPU spilt feature into exl2? I guess the need of porting all CUDA code to general CPU? w/ Dual channel DDR5 80~90GB/s, offloading few GB to CPU won't add too much latency and even probably will mitigate this issue(still relevant): https://github.com/turboderp-org/exllamav2/issues/153

**Comment by turboderp** [comment]
Moving 10% of the weights to memory that is 10x slower would double the latency on memory-bound operations. Depending on CPU compute performance, batched latency and prompt ingestion could incur a much higher penalty. So there's a very big cost for very little benefit.

Alternatively, if you can achieve perfect tensor parallelism between CPU and GPU with no overhead, you'll only reduce overall latency by a few percent, but more realistically the overhead will be very significant.

CPU offloading really only makes sense if you're not focused on performance and just want to run larger models.
