### ISSUE TITLE
TypeError: ExLlamaV2Tokenizer.encode() got an unexpected keyword argument 'return_offsets'

### ISSUE THREAD

**Issue by Rajmehta123** [turboderp/exllamav2#234]
Issue with V0.11 in tokenizer.encode() function of inference.py. 

If the response is inference and non-stream, the tokenizer fails with the following error. 

`TypeError: ExLlamaV2Tokenizer.encode() got an unexpected keyword argument 'return_offsets'`

**Comment by turboderp** [comment]
The function prototype is:

```python
    def encode(self, text, add_bos = False, add_eos = False, encode_special_tokens = False, return_offsets = False):
```

So I suspect you've got an old version of the exllamav2 package installed and it's importing that version instead.
