### ISSUE TITLE
CFG gave me OOM in tabbyAPI.

### ISSUE THREAD

**Issue by Ph0rk0z** [turboderp/exllamav2#255]
I'm using tabby with mixtral-instruct and have set autosplit. Normally this works fine with everything coming from the model configs. On large models it even works better and allows me to squeeze more context I wouldn't be able to set manually.

Having turned on CFG, the initial load also seemed fine. Unfortunately when I went to inference, GPU0 went OOM. The cards fill at 98/63 percentages and I guess CFG is too much for GPU0. There is a ton of memory on GPU1, however. Does autosplit not account for CFG?

**Comment by turboderp** [comment]
Closing this since the CFG implementation in the new generator (which Tabby uses) is completely different. Lmk if there are still issues.
