### ISSUE TITLE
CUDA out of memory, but that doesn't seem to be true

### ISSUE THREAD

**Issue by Sebastianv650** [turboderp/exllamav2#268]
Hello,
I can load exl2 models in general, using a RTX3050. But now with a just slightly bigger model (LoneStriker_SauerkrautLM-UNA-SOLAR-Instruct-4.0bpw-h6-exl2) at 5,4GB file size I get a strange OOM error despite only 5,4GB of the 8GB are used:

CUDA out of memory. Tried to allocate 38.00MiB. GPU 0 has a total capacity of 8.00 GiB of which 1.46 GiB is free. Of the allocated memory 5.35GiB is allocated by PyTorch, and 84.82 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_size_mb to avoid fragmentation.

As only 84MB are unallocated I don't think the suggestion in the error message is applicable. Any ideas what I could try?

I'm running Windows 10 and oobabooga WebUI.

**Comment by turboderp** [comment]
Loading a model takes somewhat more VRAM than the size of the weights on disk. There's also a cache (context) and a number of buffers required for inference.

Sadly, Torch's out-of-memory messages are a kind of useless. It'll usually say it failed to allocate a small amount of VRAM while a lot more is "free". But in reality that memory isn't free. One way to check would be opening Task Manager to see the actual VRAM usage as the model is loading.

SOLAR seems like it should just about fit on a 3050, but it's a tight fit so maybe you can troubleshoot by reducing the context size a little.

**Comment by Sebastianv650** [comment]
Taskmanager confirms the 5.4GB reported by the error message. I'm aware of the space needed for caches and context, but my guess was that it might work as I'm able to use for example a 3bpw exl2 model of Tiefighter 13B with 4k context and 8bit cache enabled. In this case, the VRAM is about 7.5GB used.

With the LoneStriker_SauerkrautLM-UNA-SOLAR-Instruct-4.0bpw-h6-exl2 model, it fails even at 1k context and 8 bit cache.

If you think it's a real out of VRAM thing, than it's OK and I have to stick to smaller models.
