### ISSUE TITLE
We should use exllama1 for GPTQ and exllama2 for exl2?

### ISSUE THREAD

**Issue by BadisG** [turboderp/exllamav2#28]
I've done some perplexity test, and because GPTQ (act_order + groupsize 32) is a 4.625 bit average, it should be compared to exl2 bpw = 4.625, and that's what I did
https://huggingface.co/TheBloke/Synthia-13B-GPTQ/tree/gptq-4bit-32g-actorder_True
https://huggingface.co/latimar/Synthia-13B-exl2/tree/4_625-bpw-h6

Here are the results:
![ertee](https://github.com/turboderp/exllamav2/assets/110173477/383c755e-a71d-45fd-b49a-07d739e682c5)

The conclusion is this one:
- Only use exllama1 for GPTQ models
- exllama2 + exl2 is giving the best results overall

I'm just a bit sad that exllama2 gives worse results than exllama1 when compared on the same exact settings, if exllama2 was as precise as exllama1, that 4.98 perplexity would be even lower.

But if those results are the same for all models, it will make GPTQ obsolete yeah, and that's thanks to the variable quant, and not really because of the new loader

**Comment by turboderp** [comment]
The variable quants and the implementation are tied together, and there are a bunch of factors to account for if you want a true apples-to-apples comparison. While 4.625 bpw is equivalent to 32g, EXL2 also quantizes the head layer, so it still uses somewhat less memory for weights than GPTQ 32g. You also want to make sure that the calibration data is the same for the GPTQ and EXL2 versions.

There's even a particular pitfall with Synthia-13B, which I've found in some instances saved in BF16 format. That throws away 3 bits of the fraction per weight (compared to FP16), so it can have a substantial impact on quantization.

My time (sadly) isn't unlimited, but I'm working on a set of tests to compare the actual impact of EXL2 quantization vs GPTQ and maybe llama.cpp as well. Coupled to that I'm also going to be revisiting the kernels at some point to look at losses owing to the half-precision math and various (sometimes arbitrary) choices for how sums are accumulated and when and how they get rounded along the way. It all takes time.

**Comment by BadisG** [comment]
I think the exl2 quant method is fine, you can see it's better than GPTQ overall, my problem is more with the new loader itself. When you compare exllama1 vs exllama2 on the same gptq quant, the results are worse for exllama2
![dzdz](https://github.com/turboderp/exllamav2/assets/110173477/7523298f-3664-46bb-ac62-93caf1f47488)

![zrz](https://github.com/turboderp/exllamav2/assets/110173477/64144891-8e20-409b-bc4e-8ef039e0422e)

**Comment by turboderp** [comment]
Well, as I said I am going to revisit the kernels specifically with an eye towards precision loss in the half-precision math. So there may be improvements coming up.
