### ISSUE TITLE
InternLM2 Support

### ISSUE THREAD

**Issue by brucethemoose** [turboderp/exllamav2#283]
It uses custom modeling/tokenizer code like Yi used to: 

https://huggingface.co/internlm/internlm2-chat-20b

It may or may not already work, or work with a simple repacking hack to "llamafy" it? Consider this a WIP tracking issue, I am downloading it to test right now.

**Comment by intervitens** [comment]
There are llamafied versions, they do seem to work as is with ExllamaV2.
https://huggingface.co/chargoddard/internlm2-20b-llama

**Comment by turboderp** [comment]
Does anyone know what the llamafication entails? It looks like the models just need tensors renamed and the QKV tensor split into separate Q, K and V tensors. But the safetensors files are substantially larger.

**Comment by brucethemoose** [comment]
This has kinda dropped of my radar, but one thing the custom code implements is its own rope scaling.

**Comment by brucethemoose** [comment]
See: https://huggingface.co/internlm/internlm2-chat-20b/blob/main/modeling_internlm2.py#L169-L214
