### ISSUE TITLE
Calibration data format clarification

### ISSUE THREAD

**Issue by Qubitium** [turboderp/exllamav2#29]
It is unclear how the calibration data should be structured for parquet. 

I assume it is just array of objects with string "text" as the only column/attribute?

**Comment by turboderp** [comment]
It just reads the first *n* rows from the Parquet file, tokenizes them and concatenates them into an *n* \* *m* token sequence, then arranges it into *n* rows of *m* tokens each.

**Comment by Qubitium** [comment]
Thanks for notes. It helped a lot.  

For those that want to manually make parquets, just make an array of text blobs is enough:

```python
import pandas as pd
df = pd.DataFrame(data=array_of_texts)
```

Also note that exllama v2 also impose on a minimal token size calculated by num_rows * length so if you set calbration to 100 rows (default) and 2048 tokens (default) but your dataset doesn't have 100 x 2048 tokens, it will throw a not-enough tokens error.

**Comment by eigeen** [comment]
I am doing quantization for the first time. I would like to know how many rows are normally required for calibration?

And should I provide instruction or output columns for calibration data?

**Comment by Qubitium** [comment]
@eigeen  I don't think there is a consensus on best calibration data. You can use your own training data (instruction+output), basically the same text blob thing you sent to the model to train. The model trains on the combination of your instruction+output = single text blob so I would think the calibration data should also mimic the training data exactly.

**Comment by eigeen** [comment]
> @eigeen I don't think there is a consensus on best calibration data. You can use your own training data (instruction+output), basically the same text blob thing you sent to the model to train. The model trains on the combination of your instruction+output = single text blob so I would think the calibration data should also mimic the training data exactly.

Thanks for your help. I'll try it later.
