### ISSUE TITLE
Marlin from the GPTQ guys

### ISSUE THREAD

**Issue by Jeduh** [turboderp/exllamav2#295]
Hi TurboDerp,

Could [Marlin](https://github.com/IST-DASLab/marlin) be used in ExLlamaV2?

Best wishes,
Jeduh

**Comment by turboderp** [comment]
It's a substantially different kernel and it's very tailored for 4-bit weights. I haven't studied the kernel in too much detail, though, so I don't know which of the optimizations could be carried over.

**Comment by Jeduh** [comment]
Thank you!
