### ISSUE TITLE
Convert/Quantizer bf16 support

### ISSUE THREAD

**Issue by Qubitium** [turboderp/exllamav2#30]
Currently using a finetuned model loaded/trained using bf16. Upon calling the convert.py on the checkpoint, it throws unexpected bf16 error.  

```
CUDA_VISIBLE_DEVICES=0 python convert.py -c train.parquet -r 200 \
 -i  /checkpoint-136 \
 -b 4.625 -hb 6 \
 -o test_quant 
```

```
Traceback (most recent call last):
  File "/home/exllamav2/convert.py", line 53, in <module>
    model.load(lazy = True)
  File "/home/exllamav2/exllamav2/model.py", line 227, in load
    stats = self.set_device_map(gpu_split or [99999])
  File "/home/exllamav2/exllamav2/model.py", line 185, in set_device_map
    footprint = module.weight_footprint()   # Footprint, in bytes
  File "/home/exllamav2/exllamav2/attn.py", line 109, in weight_footprint
    self.q_proj.weight_footprint() + \
  File "/home/exllamav2/exllamav2/module.py", line 114, in weight_footprint
    self.footprint = self.load_multi(["weight"], measure = True)
  File "/home/exllamav2/exllamav2/module.py", line 67, in load_multi
    size += _tsize(st, self.key + "." + k)
  File "/home/exllamav2/exllamav2/module.py", line 23, in _tsize
    else: raise ValueError(f"Unexpected datatype {dtype}: {key}")
ValueError: Unexpected datatype BF16: model.layers.0.self_attn.q_proj.weight

```

### env
```
Python 3.10.10
Torch Version: 2.2.0.dev20230913+cu121
Safetensors Version: 0.3.3
Transformers: 4.34.0.dev0
```

### checkpoint config.json
```
{
  "_name_or_path": "/root/llama2-13b-hf/",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "auto_map": {
    "AutoModelForCausalLM": "flash_llama.LlamaForCausalLM"
  },
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 5120,
  "initializer_range": 0.02,
  "intermediate_size": 13824,
  "max_position_embeddings": 4096,
  "model_type": "llama",
  "num_attention_heads": 40,
  "num_hidden_layers": 40,
  "num_key_value_heads": 40,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "rope_theta": 10000.0,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.34.0.dev0",
  "use_cache": false,
  "vocab_size": 32000
}
```

**Comment by turboderp** [comment]
I'm a little skeptical of using BF16 in the first place, and what losing those 3 bits of precision means when further quantizing the model. But I am working on it.

I thought I'd found a BF16 model to test on, but it turned out it wasn't. Do you have a HF link for a model that definitely has some BF16 tensors?

**Comment by turboderp** [comment]
Well, I've spent too long looking for a BF16 model to test, so I've just added the BF16 slice type with an element size of two. Not sure how well it will work, but it should now be able to read BF16 weight tensors and convert them to FP16 when loading.

**Comment by Qubitium** [comment]
Yeah. I don't know of a public bfloat16 model to test either. The one I have is company property so I can't upload it and looks like based on your own tests, many of the models uploaded to the HF repo are mislabeled. 

For now we are working around the problem by retraining the model where the llama2 is loaded as default f16 but training is still bf16 so that when model/checkpoint saves, it is still f16. Before we were loading and training as bf16.

**Comment by ashwincc** [comment]
Successfully convert b16 llama2-7b model. Just had to restart conversion due to memory issues. But it resumed perfectly.
Sysytem specs: 32GB RAM, 12 GB VRAM(3080Ti)

```
python test_inference.py -m ./model/converted/ -p "Once upon a time,"
 -- Model: ./model/converted/
 -- Options: ['rope_scale 1.0', 'rope_alpha 1.0']
 -- Loading model...
 -- Loading tokenizer...
 -- Warmup...
 -- Generating (greedy sampling)...

Once upon a time, there was a little boy who lived in a village. 1. The little boy was very naughty. 2. He was always fighting with other children. 3. He was always breaking things. 4. He was always making trouble. 5. He was always getting into trouble. 6. He was always getting into fights. 7. He was always getting into trouble. 8. He was always getting into trouble. 9. He was always getting into trouble. 10. He was always getting into trouble. 11. He was always getting into trouble. 12

Prompt processed in 0.01 seconds, 5 tokens, 379.03 tokens/second
Response generated in 0.81 seconds, 128 tokens, 158.43 tokens/second
```

**Comment by Thireus** [comment]
Does anyone have some benchmarks for float16 vs bfloat16 quality impact post-quantization?

**Comment by Thireus** [comment]
> I thought I'd found a BF16 model to test on, but it turned out it wasn't. Do you have a HF link for a model that definitely has some BF16 tensors?

https://huggingface.co/Thireus/WizardLM-70B-V1.0-BF16/

**Comment by turboderp** [comment]
There are still some open questions around the loss of dynamic range when converting from BF16 to FP16, and whether it has an impact performance during or after quantization. I'll close this issue for now anyway, since BF16 models no longer fail to convert.
