### ISSUE TITLE
Typo in conversion/qparams.py

### ISSUE THREAD

**Issue by 4PiR2** [turboderp/exllamav2#306]
Hello! In `conversion/qparams.py` [Line 92](https://github.com/turboderp/exllamav2/blame/8be8867548d3dc88e4e6f489cc31d3177c94bd8b/conversion/qparams.py#L92) you mistyped `+=` as `++`. This error has been there since the initial commit.

```
        total_bits += groups * 16                           # q_scale_max
        total_bits += groups * (16 + 16)                    # q_groups
        total_bits += groups * columns * self.scale_bits    # q_scale
        total_bits ++ rows * 32                             # q_invperm        <--  your typo
```

**Comment by turboderp** [comment]
This would have caused a slight miscalculation in the total bitrate. Very minor so likely no significant impact, but definitely should be fixed. Thanks for noticing.
