### ISSUE TITLE
Build from source issue in conda environment

### ISSUE THREAD

**Issue by kibilogic** [turboderp/exllamav2#314]
issue:  seems to be the "package is ignored due to missing configuration"?

snippet for brevity of the problem:

"....setuptools\command\build_py.py:207: _Warning: Package 'exllamav2.exllamav2_ext' is absent from the `packages` configuration.
!!

        ********************************************************************************
        ############################
        # Package would be ignored #
        ############################
        Python recognizes 'exllamav2.exllamav2_ext' as an importable package[^1],
        but it is absent from setuptools' `packages` configuration.

        This leads to an ambiguous overall configuration. If you want to distribute this
        package, please make sure that 'exllamav2.exllamav2_ext' is explicitly added
        to the `packages` configuration field.

        Alternatively, you can also rely on setuptools' discovery methods
        (for example by using `find_namespace_packages(...)`/`find_namespace:`
        instead of `find_packages(...)`/`find:`).

        You can read more about "package discovery" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

        If you don't want 'exllamav2.exllamav2_ext' to be distributed and are
        already explicitly excluding 'exllamav2.exllamav2_ext' via
        `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
        you can try to use `exclude_package_data`, or `include-package-data=False` in
        combination with a more fine grained `package-data` configuration.

Receive error following this command: python setup.py install --user

**Comment by turboderp** [comment]
It's not an error, just a warning because `setuptools` keeps changing. I'm not sure what they'll come up with next, but at least for now this shouldn't prevent the package from installing.

I'll be updating the README shortly, but you can use `pip install .` instead of `python setup.py install` and you won't get that warning (for some reason).

**Comment by kibilogic** [comment]
Thanks...I've managed to resolve that issue part of the error may have had to do with the version of python I was using. Of course I'm now running into an issue with flash_attn. Currently looking into that, I'm running on Windows and there have been some success with others that have solved it. I will create a new thread for that. Thanks.
