### ISSUE TITLE
ExLlamaV2Embedding can't be unloaded if it failed to load

### ISSUE THREAD

**Issue by bjj** [turboderp/exllamav2#316]
```
    def unload(self):

        del self.embedding
        self.embedding = None
```

This means model also can't be unloaded if it (partially) failed to load due to running out of memory

**Comment by turboderp** [comment]
I'm a little confused. Would unload() raise an exception?

**Comment by bjj** [comment]
Turns out `del self.embedding` is an error if the attribute doesn't exist. It's not even necessary according to my understanding: Setting to `None` is just as good.

(that attribute doesn't have an initializer, it just has a type)
