### ISSUE TITLE
what is `path_to_model` in the starter command in the readme ?

### ISSUE THREAD

**Issue by hemangjoshi37a** [turboderp/exllamav2#318]
I am little bit new here so dont know what does it mean by `path_to_model` here . where to download this model files ?

**Comment by turboderp** [comment]
You can download them from Hugging Face. For instance [here](https://huggingface.co/turboderp/Llama2-7B-chat-exl2/tree/4.0bpw), simple way is to click each of the arrows and stick all the downloaded files in one folder. Then use the path to that folder.

There's also `git clone` if you have `git-lfs` installed, or alternatively there's [huggingface-cli](https://huggingface.co/docs/huggingface_hub/guides/cli).
