### ISSUE TITLE
What's the best way to train ext2?

### ISSUE THREAD

**Issue by laoda513** [turboderp/exllamav2#32]
What's the best way to train LoRa?
Currently, there are no other projects that support the training of the ext2 model, right?

If I train with the non-quantized original model, the memory requirements are too high. If I use the gptq version for training, does that mean to need have both a gptq version and an ext2 format model? And it sounds like such a LoRa, when merged with ext2, might have some accuracy mismatches?

**Comment by johnwick123f** [comment]
Qlora or alpaca Lora 4 bit and gptq is probably your best bet. You could then merge the Lora and model and quantize the saved new model
