### ISSUE TITLE
Evaluate with lm-evaluation-harness

### ISSUE THREAD

**Issue by OfficialDelta** [turboderp/exllamav2#326]
Is it possible to evaluate XLM2 models with [https://github.com/EleutherAI/lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness)?

I'm trying to do this, but I'm not able to figure out how. One way I found as a workaround is using tabbyAPI to host it and connect as if it was a custom endpoint, but this doesn't allow for features like multiple choice question answering.

Another way to fix this would be if it was possible to load XLM2 models with Transformers, and I haven't found a way to do that yet.

**Comment by turboderp** [comment]
The easiest way would probably be using [TabbyAPI](https://github.com/theroyallab/tabbyAPI) to host a local OAI compatible server and then use lm-evaluation-harness with the `--model local-chat-completions`.
