### ISSUE TITLE
Is there a google colab to quantize llms using exllamav2?

### ISSUE THREAD

**Issue by JamesKnight0001** [turboderp/exllamav2#333]
I do not have the full requirements to quantize a 13b parameter model and don't want to waste credits in Vast.AI.

**Comment by Anthonyg5005** [comment]
This is probably something to ask in [discussions](https://github.com/turboderp/exllamav2/discussions) but here I found a colab from [llm-course](https://github.com/mlabonne/llm-course)
[![Colab](https://img.shields.io/badge/Colab-F9AB00?style=for-the-badge&logo=googlecolab&color=525252)](https://colab.research.google.com/drive/1yrq4XBlxiA0fALtMoT2dwiACVc77PHou?usp=sharing)

**Comment by turboderp** [comment]
There is that, but also the converter is designed to be run locally. I.e. if you can run the quantized model, you should also be able to quantize it.
