### ISSUE TITLE
Slow inference speed on A100?

### ISSUE THREAD

**Issue by jingzhaoou** [turboderp/exllamav2#346]
According to the benchmark info on the project frontpage: 

Llama2 | EXL2 4.0 bpw | 7B | - | - | 164 t/s | 197 t/s
-- | -- | -- | -- | -- | -- | --

I compiled ExLlama V2 from source and ran it on a A100-SXM4-80GB GPU. I got 

```
Response generated in 8.56 seconds, 1024 tokens, 119.64 tokens/second
```

which seems quite slow compared with the benchmark number. 

The text sent to ExLlama V2 is shared here: [prompt_llm_proxy_sip_full.txt](https://github.com/turboderp/exllamav2/files/14355039/prompt_llm_proxy_sip_full.txt)

The model is `turboderp/Llama2-7B-exl2` with revision `4.0bpw`. I wonder if the speed I got is expected or somehow I missed some important steps. Your help is highly appreciated.

**Comment by turboderp** [comment]
Closing this as stale, and probably outdated since a lot has been updated since then. But yes, very slow CPUs (especially virtualized ones in server instances) can be a bottleneck. Working on it. (:
