### ISSUE TITLE
Run a 34b model with a 4080 (16gb VRAM)

### ISSUE THREAD

**Issue by ScottSump** [turboderp/exllamav2#35]
I have a 4080 (I know but work gave me a very fixed budget).  I find 13B models run with a lot of headroom so I'd love to try squeezing in a 34B model, how would I do this.  Would it HAVE to be an Exl2 model?

**Comment by turboderp** [comment]
34B should be possible in 16 GB, at a low enough bitrate. Something like 2.7 bits, maybe limiting context size to 10k.. and then it might just work. But it's another extremely tight fit.

**Comment by ScottSump** [comment]
Oh, read through about 10 times and don't think I understood until know.  So it the feature of EXL2 that you can change the bitrate? Is that possible in GPTQ format as well?  I'm sorry for the junior questions, I spent hours trying to figure it out and just couldn't.

**Comment by turboderp** [comment]
Sorry for missing this. I'll close the issue, but just to answer your questions:

ExLlamaV2 only supports 4-bit GPTQ models. I'm actually not sure what would happen if you tried to convert an already quantized model, but even if it works you're not likely to get great results. And in any case you couldn't use the 3-bit GPTQ model as an input.
