### ISSUE TITLE
Integrating Medusa

### ISSUE THREAD

**Issue by KaruroChori** [turboderp/exllamav2#36]
How realistic would it be to integrate [Medusa](https://github.com/FasterDecoding/Medusa) with exllamav2?
Assuming their claims are valid, if combined with speculative decoding this could significantly boost the average performance for inference tasks.

**Comment by turboderp** [comment]
I'm very interested in that technique, yes. I wouldn't speculate as to whether or not you can get good predictions about future tokens from the last hidden state, but it sounds plausible, and the results they're reporting are comparable to using a draft model, so I guess they're on to something.

Apparently they're just training new head layers and adding them to the model, and I don't see why that wouldn't work with ExLlamaV2. Once I have the time, of course.

**Comment by kir-gadjello** [comment]
Recently medusa heads trained for popular models such as mixtral-instruct became available: https://huggingface.co/text-generation-inference/Mixtral-8x7B-Instruct-v0.1-medusa
This might be the chance to reconsider medusa integration
