### ISSUE TITLE
Size for reserved vram for cache way bigger then needed for cache_4bit?

### ISSUE THREAD

**Issue by ParkhutRoman** [turboderp/exllamav2#370]
It's more likely calculating for cache_8bit size to be reserved. If size reserved calculated for 8bit bigger then free vram, exllamav2 continue to work until vram is full without clearing cache. For example with 12k context I have no problems(size like 8bit), if I set 18k I see that vram for cache is free(but must be reserved), I can generate 1 full context response (18k) and with 2 one(same 18k size) - crash.

**Comment by turboderp** [comment]
It's definitely allocating half the size for Q4 compared to FP8, and the constant overhead should be the same. Can you say a little bit more about your setup? Are you running in Ooba?

**Comment by ParkhutRoman** [comment]
Strange i don't get Notifications for reply, exllamav2-0.0.16 seams fixed all, i'm tried Ooba and tabbyAPI, Ooba with exllamav2_hf worked even on exllamav2-0.0.15 clearing cache when tabbyAPI was crashing on exllamav2-0.0.15. now is ok.
