### ISSUE TITLE
Support C4AI Command-R

### ISSUE THREAD

**Issue by djmaze** [turboderp/exllamav2#372]
People say it is really useful for RAG & agent use, and it also has good multilingual support. Would be nice to have an efficient version using EXL2.

**Comment by JoeySalmons** [comment]
Looks like EXL2 quants are up: https://huggingface.co/turboderp/command-r-v01-35B-exl2

@turboderp Thank you!

**Comment by turboderp** [comment]
Yep, supported in 0.0.16

**Comment by djmaze** [comment]
I guess chat completions are not supported because they use a [custom tokenizer](https://huggingface.co/CohereForAI/c4ai-command-r-v01/blob/main/tokenization_cohere_fast.py#L193)?
