### ISSUE TITLE
Rope scaling, length, measurement_length during EXL2 quantization

### ISSUE THREAD

**Issue by grimulkan** [turboderp/exllamav2#38]
Is it important to use the same RoPE scaling method as used in training, during quantization as well (linear, change of base like in codellama, alpha)? Does the current code support that if it is specified in config.json in the model folder?

I see the inference supports it, but wondering if it makes a difference during quantization.

I suppose the dataset also has to have data items that are long enough for that length, for this question to make sense. The original GPTQ I think just picked random "length" tokens from C4 or wikitext after concatenating all the data samples, so as long as there were enough inputs, it always made up some tokens to whatever length you asked it to measure at. Does EXL2 do this, or do we have to make our own dataset?

I also don't know about the VRAM requirements. Does EXL2 need enough VRAM to store the biggest unquantized layer + entire dataset? In original GPTQ we could offload the dataset to RAM (at the cost of a lot of speed), and only needed to have enough VRAM to load the biggest layer.

Hope my questions make sense.

**Comment by Grimulkan** [comment]
Answering some of my own questions: with the latest pull and slight modifications, it seems to work, and far more efficient than AutoGPTQ with flash attention 2!

Changing the theta (like in codellama) is automatically picked up by the model, but there is no way to tell it to use a linear scale or alpha. This can be specified in the `config.json` file like so (example is for a 4x linear scaling factor to 16K in llama-2, base theta):
```
  "max_position_embeddings": 16384,
  "rope_scaling": {"type": "linear", "factor": 4.0},
  "rope_theta": 10000.0,
```

`config.prepare()` picks up `max_position_embeddings` and `rope_theta`, but not `rope_scaling`. But the rest of the code does work. I tested it by inserting the following lines in `convert.py`:
```
config.model_dir = in_dir

#Test RoPE Scaling: Load from config.json
with open(os.path.join(config.model_dir, "config.json")) as f:
    read_config = json.load(f)
    if "rope_scaling" in read_config:
        rope_scaling_config = read_config["rope_scaling"]
        if "type" in rope_scaling_config and "factor" in rope_scaling_config:
            if rope_scaling_config["type"] == "linear": #Linear scaling
                config.scale_pos_emb = int(rope_scaling_config["factor"])
            else: #NTK-alpha
                config.scale_alpha_value = float(rope_scaling_config["factor"])

config.prepare()
```

I stepped through and checked that the sin/cos tables were being generated correctly.

Also, the data items are indeed concatenated like AutoGPTQ used to do to make up whatever length you ask.

There is this config value that doesn't get set (and seems to default to 2048 no matter what `config.json` says for `max_position_embeddings`):
```
max_input_len: int = 2048                   # Maximum length of input IDs in a single forward pass. Sequences longer than this will be processed in multiple steps
max_attention_size: int = 2048 ** 2         # Sequences will be processed in chunks to keep the size of the attention weights matrix <= this
```
Not sure if that matters.

On whether you get better quality on quantizing with the full fine-tuned context length vs 4096, I don't know, but I have to imagine it matters. Using the correct RoPE scaling as the fine-tune almost certainly matters, so hopefully this will be patched (or added in a command line argument like the inference code).

**Comment by MB7979** [comment]
Thanks very much for the code changes to convert.py above. I was getting 300+ calibration perplexity before adding it to quantize a model with a linear rope scale factor of 8. I'm not sure if that would have flowed through to inference in real life, but I began the process again just in case. The calibration perplexity dropped to 6.

**Comment by grimulkan** [comment]
Likewise. It actually does not follow through to inference so I don't know how critical it is.

**Comment by grimulkan** [comment]
This is no longer needed, just wanted to point out. Now you just specify `--rope_scale` for `convert.py` in the command line. I don't know if it reads the `config.json` file though. I just manually copy the rope scale from `config.json` and add it to the command line.
