### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by insanesac** [turboderp/exllamav2#386]
![Screenshot from 2024-03-27 15-10-40](https://github.com/turboderp/exllamav2/assets/16168851/19402e02-8950-41cb-8d27-652133d5c440)

 python3 test_inference.py -m /app/Llama2-7B-chat-exl2 -p "Once upon a time"

I get MemoryError as shown in the screenshot. The same happens when I run chat.py.
I tried logging to know which file was causing the error. output.safetensors is the cause.

I have an Ubuntu 22.04 machine with nvidia T4 GPU. The machine also has 64GB RAM.

**Comment by turboderp** [comment]
Are you sure the .safetensors file isn't corrupt?

**Comment by insanesac** [comment]
I thought that was the case too. So switched branches -  8.0bpw, 6.0bpw and 4.0bpw. The same error. Let me download the files individually and then see if that solved the issu

**Comment by insanesac** [comment]
Looks like it was corrupted. Downloaded the files individually fixed it. Thanks
