### ISSUE TITLE
Incorporate RAG with Exllamav2 

### ISSUE THREAD

**Issue by insanesac** [turboderp/exllamav2#387]
Hi,

I want to integrate RAG with exllamav2. I could not find any relevant stuff online and hence asking here. I have a langchain based implementation for RAG which runs fine with hf and llama_cpp_python, but i want to use exllamav2 instead. Any suggestion/link is welcome.

**Comment by johnwick123f** [comment]
@insanesac either you could use this
https://github.com/langchain-ai/langchain/issues/8385#issuecomment-1953333714

Or implement your own RAG system which might be better? but i suppose you strictly want to use langchain and so you should use the above link.

**Comment by insanesac** [comment]
Well i dont have any strict requirements about using langchain. I just want to setup a RAG based usecase. The above link did help a lot and i was able to use add RAG to it. Thanks a lot for the help, it was a lifesaver

**Comment by werruww** [comment]
Well, I don't have any strict requirements for using langchain. I just want to set up a RAG-based use case. The link above helped a lot, and I was able to use the RAG plugin. Thanks so much for the help; it was a lifesaver.

Can you share your code with us?
RAG

**Comment by remichu-ai** [comment]
I think your best way to approach it is implement rag with openai plugin. You then can use tabby api to run openai compatible server witb exllamav2 backend. This is how most people do cause almost everyone have their api server designed to be compatible with openai spec
