### ISSUE TITLE
Cannot split from textgen?

### ISSUE THREAD

**Issue by Ph0rk0z** [turboderp/exllamav2#4]
Since gpu split is an arg and not config I think it cannot be used externally.

```
    split = None
    if args.gpu_split: split = [float(alloc) for alloc in args.gpu_split.split(",")]
    model.load(split)
```

Also can't set rope base I think. Only pos emb scale and alpha value.

It is already integrated as pr: https://github.com/oobabooga/text-generation-webui/pull/3881

**Comment by oobabooga** [comment]
I have implemented gpu_split for both ExLlamav2 and ExLlamav2_HF. I think that it should work.

**Comment by Ph0rk0z** [comment]
Thanks! It seems to be good.
