### ISSUE TITLE
Chat work greate but inference broken. Why?

### ISSUE THREAD

**Issue by 50Bytes-dev** [turboderp/exllamav2#43]
If I use inference the answer breaks down
<img width="493" alt="image" src="https://github.com/turboderp/exllamav2/assets/58135997/b98ce8dc-c2bb-4189-aefe-89a3cefc7c0e">

But in chat mode, everything is fine
<img width="972" alt="image" src="https://github.com/turboderp/exllamav2/assets/58135997/5b861a3b-63c8-4250-b33c-bc0ecc507b0e">

I use examples with my prompt.

**Comment by 50Bytes-dev** [comment]
Works in llama and codallama mode. If you set it to raw mode, everything breaks down too

**Comment by 50Bytes-dev** [comment]
If tokenizer.encode(text, **add_bos = True**) everything works fine. 
But, if tokenizer.encode(text, **add_bos = False**) then the answers break down

Can you fix it?

**Comment by turboderp** [comment]
I think this is down to what model you use. Some models are tuned to expect BOS at the start of every sequence and won't perform well without it. Llama-chat models require a specific format for the prompt including EOS and BOS in various places. The base models don't want BOS. And all the various finetunes have their own preferences.

The "raw" mode in the chat example is intended to work with a base model and some other finetunes that don't use BOS.
