### ISSUE TITLE
Quantization subtly broken recently?

### ISSUE THREAD

**Issue by QM60** [turboderp/exllamav2#44]
Recently I've been attempting to quantize some models and noticed some severely bad numbers in the log. The latest one has
`-- Calibration perplexity (base): 890.5957`
which seems like something is very wrong. But the script finishes without complaint, and produces a seemingly valid model.

I had success with commit 63f50d72de80634275ccb6a42390bda2a37f3040, before the recent changes, and got reasonable perplexity numbers. Same calibration dataset in both cases (https://huggingface.co/datasets/wikitext/blob/refs%2Fconvert%2Fparquet/wikitext-2-v1/test/0000.parquet). Is there a known-good dataset that you test with? The lack of a standard leads to guessing, although that may be what you want if you're trying to shake out bugs.
I confirmed that the new quants show worse perplexity than the old (from 63f) by about 0.08, which seems rather large, although maybe not enough to be noticed. If other people are getting this, I worry we'll have a bunch of slightly broken quants floating around until the end of time. If I'm the only one seeing this, I don't mind as much.

Here's what it prints as a sample.
```
 -- Tokenizing samples...
 -- First 50 tokens of dataset:
    ' = Robert <unk> = \n  Robert <unk> is an English film , television and theatre actor . He had a guest @-@ starring role on the television series The Bill in 2000 . This was followed'
 -- Last 50 tokens of dataset:
    'explains . For example , when Butler was <unk> in late 2010 , Stevens challenged his team : " this [ 46 % defensive field goal percentage ] is where we are . This isn \'t acceptable to get'
```

If nothing else, it may be wise to have an early crash/warning on absurd ppl since the nasty numbers only show up after generating measurement.json currently. Which makes it tedious to verify the problem. And some may not even see it.

**Comment by Grimulkan** [comment]
I also had a few models quantize to high PPL and was trying to figure out the problem. Are you saying you didn't see it in the previous commit for the same dataset and model?

Do we have to basically finish the entire measurement to see it, or do you know of a way to compute it earlier in the code?

**Comment by Panchovix** [comment]
I have gotten it as well, so can confirm those very high PPLs happen. On TheBloke discord server, other people have reported the same as well.

Not sure where the issue is for now.

**Comment by turboderp** [comment]
It appears to be down to numerical precision issues that manifest differently based on very subtle conditions, but mostly for very large models that have been fine-tuned. I suspect fine-tuning in BF16 precision contributes to this, and the quantization involved in QLoRA may play a role as well.

In any case, the challenge is to find the specific places where numerical precision becomes an issue and either add more precision, add clamping (not allowing FP16 values to overflow to +/- inf which breaks all subsequent computation), apply some form of regularization, or whatever else is appropriate.

Good news is I've managed to reproduce what I think is the main issue people are experiencing, which seems to be a matrix inversion that fails when the input gets very large, specifically the last linear projection of the MLP on 70B models (28k x 28k Hessian), and especially with large calibration samples. The Hessian accumulates too many rounding errors and ends up having one or more slightly negative eigenvalues. Which I thought I was accounting for already, but it appears that Torch won't always throw an exception when failing to compute a Cholesky inverse, instead just producing a NaN tensor sometimes. Explicitly testing for that and shifting the eigenvalues (damping) a little more if that happens seems to have fixed it, but I need to quantize a few more models before I know for sure.

**Comment by Grimulkan** [comment]
> which seems to be a matrix inversion that fails when the input gets very large, specifically the last linear projection of the MLP on 70B models (28k x 28k Hessian), and especially with large calibration samples.

Yes, I threw in a bunch of asserts and prints to see where I got strange values, infs or nans, and also traced it to the hessian being inverted during o_proj for a 70B model, and my calibration dataset size is pretty big. It happened only for layer 9 for some reason, the first 8 didn't trip my assert.

**Comment by Grimulkan** [comment]
Don't know if there was supposed to be a fix, but I tried again with the latest pull (I thought I saw some extra code for damping that might be related). I still got NaNs during the Cholesky inverse. Will try again later if there's another update.

**Comment by Panchovix** [comment]
Turbo said that it would be recommended to re-do the measurement.json, since that one is that it gets the high ppls and then pass it on the quantization.

I've done a new measurement on Airoboros 70B 1.4.1, and the value is a expected/normal value:

```
-- Layer: lm_head (Linear)
-- Calibration perplexity (base): 6.5192
-- Optimizing...
```

Instead of the 600+ I had on commits previous than today.

**Comment by Grimulkan** [comment]
Yup, works for me too :)
` -- Calibration perplexity (base): 6.1399` (down from bazillion)
Will update after quant finishes.

**Comment by Grimulkan** [comment]
Hmm... There's still one model that won't quantize. Is everyone else having no problems?

During measurement, I get 
```
"key": "model.layers.79.mlp.down_proj",
"numel": 234881024,
"options": [
    {
        "desc": "0.05:3b/0.95:2b 32g s4",
        "bpw": 2.174290248325893,
        "total_bits": 510699520.0,
        "err": Infinity,
        "qparams": {
            "group_size": 32,
            "bits": [
                3,
                2
            ],
            "bits_prop": [
                0.05,
                0.95
            ],
            "scale_bits": 4
        }
    },
... and so on
```
and
`"base_perplexity": Infinity`

During quantization, the code gets stuck in an infinite loop:
```
 -- Target bits per weight: 4.625 (decoder), 6 (head)
 -- Max shard size: 8192.0 MB
 -- Optimizing...
 -- rfn max: inf  bpw: 2.17262
 -- rfn max: inf  bpw: 2.17262
 -- rfn max: inf  bpw: 2.17262
 -- rfn max: inf  bpw: 2.17262
... loops forever

```
