### ISSUE TITLE
Ninja Build Error for ROCm

### ISSUE THREAD

**Issue by lufixSch** [turboderp/exllamav2#46]
I get a bunch of errors when running.

```bash
python test_inference.py -m <model> -p "Once upon a time,"
```

On the first execution the process exited with the error message provided in the following File. The Output is pretty long therefore I uploaded it as a separate file

[Output of the first run](https://github.com/turboderp/exllamav2/files/12659904/logs_old.txt) 

After the first execution I noticed, that the output changed. Now I get this Error:

[Output of the second run](https://github.com/turboderp/exllamav2/files/12659919/logs.txt)

I am not sure If there are some extra steps necessary when running ExllamaV2 on ROCm. I just cloned the repository and installed the requirements as stated in the README.md (torch for ROCm was installed before).

### System Information:
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.5.1-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 20 × 13th Gen Intel® Core™ i5-13500
Memory: 31,1 GiB of RAM
Graphics Processor: AMD Radeon RX 6750 XT
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7D98
System Version: 1.0

**Comment by ardfork** [comment]
It seems like you are missing hipBLAS.

**Comment by lufixSch** [comment]
When I check with `pacman` it lists a `hipblas` package

```bash
$ pacman -Q hipblas  
hipblas 5.6.0-1
```

**Comment by lufixSch** [comment]
Pytorch is installed via pip. The venv I am using is the one I am running Oobaboogas WebUI in.

Thanks, I will try that patch later.

**Comment by lufixSch** [comment]
I tried the patch but it did not work. The Error is still the same.

Ps.: I was unable to apply the patch, therefore I changed the file manually

I tried searching for the `hipblas` library with ldconfig and got the following results:

```bash
$ ldconfig -p | grep hipblas    
libhipblas.so.1 (libc6,x86-64) => /opt/rocm/lib/libhipblas.so.1
libhipblas.so (libc6,x86-64) => /opt/rocm/hipblas/lib/libhipblas.so
libhipblas.so (libc6,x86-64) => /opt/rocm/lib/libhipblas.so
```

Not sure if that helps.

**Comment by ardfork** [comment]
Can you check #include in `exllamav2/exllamav2_ext/hip/q_gemm.cuh`? It should include <ATen/hip/HIPContext.h>.
Also, check include of `lib/python3.10/site-packages/torch/include/ATen/hip/HIPContext.h` (in your venv), it should include <hipblas/hipblas.h>.

**Comment by ardfork** [comment]
I believe that it converted it to rocblas instead of hipblas, since you are probably using a pytorch version before [this commit](https://github.com/pytorch/pytorch/commit/5379b5f9276a871834253b9b6668d0139dfba85a).

It's weird because #22 said it worked on older pytorch version (that why is was merged) but if my hypothesis is correct, it's not completely fixed. Honestly I don't really want to bother fixing and testing on old pytorch version, a new stable version should release soon and you can still install preview in the mean time (`pip3 install --pre torch --index-url https://download.pytorch.org/whl/nightly/rocm5.6`).

**Comment by lufixSch** [comment]
Installing torch for rocm5.6 fixed the problem. This solution is fine for me especially if a stable version for ROCm5.6 will be released soon.

Thanks for your help and thanks for adding ROCm support in the first place.

A small question in the end: I noticed an warning about flash-attention but the linked repository has no ROCm support. Is there a way to install flash-attention for ROCm?

**Comment by lufixSch** [comment]
> I do not have flash attention installed as it was not part of requirements.txt and exllama just silently use torch matmul attention if it's not installed. There is https://github.com/ROCmSoftwarePlatform/flash-attention but it currently only support gfx90a (MI210/MI250/MI250X)

Thanks for looking that up. I will keep an eye on that project. Maybe they will extend GPU support in the future and add flash attention 2.

I will close this issue now, as my initial problem has been solved. Thanks for all the help.
