### ISSUE TITLE
Does not access add_tokens config when creating config

### ISSUE THREAD

**Issue by alimadelshin** [turboderp/exllamav2#49]
Script only take tokenizer.model

**Comment by wangyu1997** [comment]
I meet the same problem, it seems that special_tokens has not been handled，too

**Comment by turboderp** [comment]
There is some work that still needs to be done on the tokenizer, yes, specifically regarding the various different (and sometimes conflicting) ways that various finetunes extend the vocabulary. I'm juggling a lot of things, so I'm not sure when I can get to it, but in the meantime you could consider using `transformers.LlamaTokenizer.from_pretrained` instead.

**Comment by wangyu1997** [comment]
Have this issue been solved? I can not simply replace Exllamav2Tokenizer to LlamaTokenizer since there are much calls in samplings and streamings

**Comment by turboderp** [comment]
Yes, the tokenizer will read added_tokens.json now, and you can encode the extra tokens with by setting `encode_special_tokens = True`.

**Comment by wangyu1997** [comment]
yes, i have tried this param and it can indeed encode the addition tokens, but the model will never stop when generating.

Cause the addition tokens are like "### Instruction" or "### Output", I found the model will never generate these kind of tokens when streaming, and will keep generating forever.

**Comment by wangyu1997** [comment]
I found that the default stream method in generator will not decode with 'decode_special_tokens=True'.

<img width="1050" alt="image" src="https://github.com/turboderp/exllamav2/assets/15991233/0b55eefc-a1f8-4dbd-9010-d9a58f2c8fc5">

**Comment by wangyu1997** [comment]
I suggest that 'encode_special_token' should be a global parameter of Tokenizer neither 'encode/decode' method, this will be much better.

**Comment by wangyu1997** [comment]
i modified the tokenizer in #164 , maybe this will be better ?

**Comment by turboderp** [comment]
If the model outputs things like `### Instruction` as a single token, you can reliably use the ID of that token as a stop condition. Forcing the tokenizer to turn the tokens into strings also wouldn't automatically make them stop conditions in the generator. Either way the generator needs to know when to stop generating. There is the `set_stop_conditions()` function for that purpose, which takes a list of strings and/or token IDs that will be held and cause `stream()` to return an EOS signal when they're encountered. I.e.:

For strings:

```python
generator.set_stop_conditions(["### Instruction", "\n", ...])
```

For tokens:

```python
generator.set_stop_conditions([tokenizer.extended_piece_to_id["### Instruction"], tokenizer.eos_token_id, ...])
```

Then the streaming loop should simply be:

```python
while True:
    chunk, eos, _ = generator.stream()
    do_something_with(chunk)
    if eos: break
```
