### ISSUE TITLE
Covert.py measurement "Killed"

### ISSUE THREAD

**Issue by GHBigD** [turboderp/exllamav2#504]
I have my own homebrew Model Stock merged Wizard 8x22B base model that, when I try to do a measurement pass, ultimately bombs with a "Killed." I didn't see a way to get more verbose debugging information. The model in its full bfloat16 glory loads and runs, I just cannot make a successful measurement. As I am typing this I am wondering if it is a hardware requirement issue. I spun up a much smaller instance for the measurements.

**Comment by GHBigD** [comment]
...nope...

**Comment by Pevernow** [comment]
RAM is not enough for it.

**Comment by turboderp** [comment]
"Killed" without any explanation usually means you're out of memory. Are you on Windows by any chance?

**Comment by GHBigD** [comment]
> "Killed" without any explanation usually means you're out of system memory. Are you on Windows by any chance?

Ubuntu 22.04 LTS
50 GB RAM 48GB VRAM (Single GPU)
I'm realizing now reading the hardware requirements that I was too focused on the VRAM and not the RAM. That's because I am a regular speed derp instead of turbo..

**Comment by turboderp** [comment]
For this particular model I don't think 50 GB of RAM is quite enough.

![image](https://github.com/turboderp/exllamav2/assets/11859846/a0e6f06a-5c16-49f1-b850-5554b7126f4a)

Biggest issue seems to be measuring the block-sparse MLP layers where I'm using about 64 GB of system RAM. The layers are very large and you need 13 versions of each tensor to produce 17 layer variants to measure. They have to reside somewhere, and saving them temporarily to disk probably isn't going to perform better than just using swap memory. 

They could be packed, of course, and I think I'll look into that at some point. For now it's not a priority, though. Too many other things happening. You could try with a swap partition, or try using a measurement.json from another Wizard 8x22B model perhaps.

**Comment by GHBigD** [comment]
> For this particular model I don't think 50 GB of RAM is quite enough.
> 
> 
> Biggest issue seems to be measuring the block-sparse MLP layers where I'm using about 64 GB of system RAM. The layers are very large and you need 13 versions of each tensor to produce 17 layer variants to measure. They have to reside somewhere, and saving them temporarily to disk probably isn't going to perform better than just using swap memory.
> 
> They could be packed, of course, and I think I'll look into that at some point. For now it's not a priority, though. Too many other things happening. You could try with a swap partition, or try using a measurement.json from another Wizard 8x22B model perhaps.

I spun up a 150GB instance and I can confirm it is humming along fine at the moment. At the peak, it was using 18GB of VRAM and 60GB of RAM

Thanks for the help!
