### ISSUE TITLE
Pass stop words to a model

### ISSUE THREAD

**Issue by Nikita-Sherstnev** [turboderp/exllamav2#51]
How can we pass stop words?

**Comment by turboderp** [comment]
There's still work to be done on the generators, but currently `ExLlamaV2StreamingGenerator` supports stop strings. The `set_stop_conditions` function takes a list of strings, or token IDs, or a mix of the two:

```Python
generator.set_stop_conditions(["some string", "some other string", some_token_id])
```

**Comment by Nikita-Sherstnev** [comment]
Cool, thanks!
