### ISSUE TITLE
feature request: Radix Cache

### ISSUE THREAD

**Issue by isamu-isozaki** [turboderp/exllamav2#523]
Hi! Awesome library. For the new update with the Dynamic Jobs, do you have plans on adding Radix Cache? It was an idea proposed in [SGLang](https://arxiv.org/abs/2312.07104) and the basic idea is to save KV cache of previous prompts and re-using them if a new prompt starts with a previously recorded prompt. This is pretty useful for chain of thought etc like so
![image](https://github.com/turboderp/exllamav2/assets/23430101/8ed006bc-0c8b-4858-b624-e3e58b6879d6)
I do have an implementation with outlines+previous exllama2 [here](https://github.com/blockentropy/ml-client/pull/12)

I can try contributing too although I'm not too familiar with the inner parts of this library yet. But do you think this can be a feature in exllama2?

**Comment by turboderp** [comment]
This has been a feature of the streaming generator for a long time, for a single prompt. The dynamic generator extends it to dynamically caching multiple prompts as well. See [here](https://github.com/turboderp/exllamav2/blob/master/doc/dynamic.md#prompt-caching).

**Comment by isamu-isozaki** [comment]
@turboderp oh awesome tysm!
