### ISSUE TITLE
qwen2 not supported

### ISSUE THREAD

**Issue by abpani** [turboderp/exllamav2#531]
!! Warning, unknown architecture: Qwen2MoeForCausalLM
 !! Loading as LlamaForCausalLM

ValueError:  ## Could not find model.layers.0.mlp.down_proj.* in model

**Comment by turboderp** [comment]
Qwen2 is supported, Qwen2MoE is not, currently. PRs are welcome, of course.

**Comment by turboderp** [comment]
Referring this to #545.
