### ISSUE TITLE
Gemma 2 support

### ISSUE THREAD

**Issue by rjmehta1993** [turboderp/exllamav2#532]
Please support gemma 2 architecture whenever you get time.

**Comment by Vhallo** [comment]
turboderp is already working on it.

**Comment by rjmehta1993** [comment]
Awesome. Thanks.

**Comment by iamsaurabhgupt** [comment]
waiting for this

**Comment by turboderp** [comment]
It's in the dev branch, but Gemma2 won't work in flash-attn yet until [this PR](https://github.com/Dao-AILab/flash-attention/pull/1025) is finished/approved.

**Comment by iamsaurabhgupt** [comment]
@turboderp softcapping PR is merged to flash-attention:main
so, Gemma2 support should now be available with flash_attn here as well?

**Comment by CyberNativeAI** [comment]
Any update on this? I tried yesterday on 27b and the model seems confused.

**Comment by waterangel91** [comment]
It is working for me both 9b and 27b. Maybe u can try other quant. I am using 5.0bpw

**Comment by CyberNativeAI** [comment]
> It is working for me both 9b and 27b. Maybe u can try other quant. I am using 5.0bpw

It does quantize 27b but w/o flash-attn, and the quality seems to suffer.

**Comment by turboderp** [comment]
Have you updated both ExLlamaV2 and Flash Attention? You need at least versions 0.1.7 and 2.6.0, respectively.

Also, in what way is it confused?

**Comment by waterangel91** [comment]
i am using the quantized version from huggingface and not quantize my self. Didnt noted sny problem

**Comment by turboderp** [comment]
There have been issues with Gemma2 in many different implementations. They're slowly being worked out but it wouldn't surprise me if axolotl has had some too. You can perhaps run the FP16 model without quantizing to verify.

**Comment by iamwavecut** [comment]
My latest attempts to deploy any Q8 and lower EXL2 quant of Gemma 2 variants failed with the same pattern. 

First it generates several sentences just fine, but suddenly breaks and starts to generate total garbage, like so:
```
🕒 21:37:43 ✅ Хуaminya! так им дела者が... корось?                                                                                                                            0.00ss
🕒 21:37:50 ✅ Hmm... (ex) [something erotic for me]. *oh*, yes!
🕒 21:37:59 ✅ ... [ ]* 😏 ( ) * ,,,,,,,,,,.,.,, ,,,. .. .. ... ... ... ... ;;''"'?...???!!!?!?!?!?!... . ... ... ... ... ... ... ... ... ., :,""""" """;...
🕒 21:38:01 ✅ ДSegments themselves to the extent of a mis in an out for that they's been like me and I am sure one thing is it be more so you do something will make themselves this way around my own
🕒 21:38:07 ✅ "А ведь time of the light to the next thing that they'll go for." you!
🕒 21:38:12 ✅ Заfics! Вы coming to a good deal no live it is like you'll give me nothing?
🕒 21:38:17 ✅ А... "так? ...", что; 😏 snap?"show** */ * **whore* : [ ] ; ,,,,.,,,..
🕒 21:38:22 ✅ Мerrmsg 아니라":{"**"***"* *** ** * *" *""""" """ ""*" ****?***** *****/????? *******"? _*? *_?*%.* %*. "*!%?"%." ****?"s'"` Normdatei `.`.""" ':*'"'* ''''''''"""" '' ````'` _... .. . : ,,,,,,.,,,.,".,..,.. -"... ...".." ., ... ... ." ,"r... ,,...
🕒 21:38:28 ✅ Вот pure — and they's got it for the sake of them by means that way— the one to be sure in this is a thing! That you will get with respect toward nothing else but an object?
🕒 21:38:33 ✅ ВаaddData... * **"по**; *?* чтоsoever*.
🕒 21:38:38 ✅ "А б*******!""Что* *****»!!!?" ???!!!! ?????!!!"?? !!!!!!!!"!!!!!!!!...," *****************!*"**"*. . */ /.*; ;;:*..***...****?!/""" """""""'!',' |'' ' '' "'"'*' '*.''* ..." .. ... ***?*,*.,,,,,,,. ,,,,, ,,.,,.; .; : ', ... ...:;;... :,...,... ... .,...*;,; ** **** ******...
🕒 21:38:43 ✅ **... «come's a bit of the dark to me in my life!
🕒 21:38:48 ✅ ... fuck you guys and your magic tricks! Let's get it done in style like that feeling; a bit of the way on to this one thing?
🕒 21:38:53 ✅ По тебе he's got to the place of a magical and wondrous forest in his eyes that is an enchanted one by it!
🕒 21:38:56 ✅ ПроIANGLES!
🕒 21:39:01 ✅ Так fuck in the darkness of a few things and nothings to be what I'm so much at this point that is all it;
🕒 21:39:06 ✅ Damn it! Who's this? You got your lucky ship for me to see you in a hurry and yours too on my own boat—and all kinds;
🕒 21:39:08 ✅ Поздвань! (о ©©()) )* * |)) ;
```

I don't know for sure, but I can assume, anecdotally, that the KV cache gets somehow corrupted after getting saturized enough.

**Comment by iamwavecut** [comment]
@turboderp mentioning to bring attention

**Comment by turboderp** [comment]
Just to be clear, this is on version 0.2.0?

**Comment by iamwavecut** [comment]
@turboderp sorry for late reply, but yes, it was, now on 0.2.1 and it's still reproducing

**Comment by iamwavecut** [comment]
@turboderp well, now on 0.2.1 and I managed to get this on other llama3.1 based arch model lower quant, so may-be not gemma specific. I'll dig some more and create a new issue if it's reproducible

**Comment by iamwavecut** [comment]
@turboderp next update -- everything is fine!

Two things happened:
- I've found that I lost the `<bos>` token in y input.
- Reinstalled `exllamav2`@0.2.1 from scratch and req-ed the model.

I believe the lack of `<bos>` token got output somehow unterminated in batch mode, thus leading to output corruption.
