### ISSUE TITLE
Multiple regex/ influence generation

### ISSUE THREAD

**Issue by waterangel91** [turboderp/exllamav2#536]
I would like to ask is if there is an efficient way to achieve the below generation:
```
" Answer: {regex pattern0} (if regex_pattern0 return A -> "hello" else "hi") {regex pattern1}, (if regex_pattern0 return A -> "ok" else "not ok")  {regex pattern2}"
```

Basically i have a few different generations for 1 prompt where depending on the model answer for the regex pattern, it will influence the later generation. Currently, i  break the generations into a few rounds, which basically mean i call the generation 3 times like below. The whole prompt will need to be run again each time eventhough there is only a bit changes at the end:
```
Answer: {regex pattern0}
Answer: {regex pattern0} (if regex_pattern0 return A -> "hello" else "hi") {regex pattern1},
Answer: {regex pattern0} (if regex_pattern0 return A -> "hello" else "hi") {regex pattern1}, (if regex_pattern0 return A -> "ok" else "not ok")  {regex pattern2}
```

Hope my example is not too confusing, if there is any efficient way that i can adopt, just let me know. Or maybe the performance improvement wont be much with Q4 cache (cause majority of the prompt already cached?)

**Comment by turboderp** [comment]
This is Guidance, essentially, or some version of it. And some sort of smart filter with a scripting language would be a very nice feature to have but also a big undertaking, so I'm not sure when I can fit it in. I'll probably add callbacks to the dynamic generator soon, with some well-defined methods for adjusting sampling params and swapping out filters mid-generation.

In the meantime you could rely on prompt caching in the generator. If you run a completion for `X` to produce `XY`, at the end of that generation the cache will contain the keys/values for `XY`. So if you subsequently generate from a prompt of `XYZ`, only `Z` will be ingested. It should be efficient to do multiple rounds of generation this way.

At least this is true for the streaming generator and the dynamic generator, and the dynamic generator extends it to multiple sequences as well. The base generator (with `generate_simple`) doesn't support prompt caching.

**Comment by waterangel91** [comment]
Thank you for the clarification. Understand you need to focus on other priiroties. 
One more question i have is, how much will the cache store? If i am running generation as async, and there is other generation request come between my X and XY ( X -> X2 -> XY instead of X -> XY), will the cache be overwritten? Or the cache will be stored until the accumulated cache is more than the context length only then it will be freed up?

**Comment by turboderp** [comment]
The cache retains as many *pages* as it can. Each page is 256 tokens. When it fills up it will evict the oldest (least recently used) pages first. So if you're switching between two or more contexts this way they should both be able to coexist, as long as the cache is large enough. Note that it also deduplicates pages, so if you run inference on:

- `ABCDEx`
- `ABCDEy`
- `ABCz`

If a character represents a page and the cache isn't filled up and has to start evicting pages, it would contain 8 pages, afterwards:

- `A`
- `B` valid for prefix `A`
- `C` valid for prefix `AB`
- `D` valid for prefix `ABC`
- `E` valid for prefix `ABCD`
- `x` valid for prefix `ABCDE`
- `y` valid for prefix `ABCDE`
- `z` valid for prefix `ABC`

If the next prompt you run is `ABCDw`, it would add one more page to the cache and reuse those first 4 pages.

**Comment by waterangel91** [comment]
Thank you very much for the detail explanation. Appreciate it. Didnt know the backend is so efficient!!
