### ISSUE TITLE
Feature request: encode special tokens

### ISSUE THREAD

**Issue by vt404v2** [turboderp/exllamav2#54]
Unfortunately exllamav2 can't handle with special tokens like <s>, </s>, <unk> in prompt. What I mean is that I can add the `bos` and `eos` tokens by using ExLlamaV2Tokenizer.encode, but it is not possible to add them elsewhere in prompt, because tokenizer will encode them as text. For example `tokenizer.encode("...<s>....") will be encode like tokenizer.encode("...") + tokenizer.encode("<")+ tokenizer.encode("s")+ tokenizer.encode(">") + tokenizer.encode("...")`. exllamav1 has parameter for this, named `encode_special_characters `

**Comment by Grimulkan** [comment]
v2 has `encode_special_tokens`  now I believe

**Comment by turboderp** [comment]
Yes, I added that yesterday. Or the day before. Idk, it's all a blur. 

I'm not completely sure the implementation is robust yet. There are some subtleties around whitespace next to special tokens that might need ironing out, and also the HF format is quite chaotic. I'm only reading the `added_tokens.json` file for now and I don't really have a plan for what to do with `generation_config.json`, `special_tokens_map.json` or `tokenizer_config.json`, all of which seem to have something to do with extending the vocabulary. I especially don't know what to do when they conflict with each other. So probably if you want to *perfectly* imitate Transformers, for now you should use Transformers' tokenizer class.

**Comment by Qubitium** [comment]
> HF format is quite chaotic

Understatement of the year.  =) I go on an one week vacation, come back, checkout latest transformers, and I feel like freshman in high school again. You know nothing John Snow!

**Comment by Grimulkan** [comment]
> > HF format is quite chaotic
> 
> Understatement of the year. =) I go on an one week vacation, come back, checkout latest transformers, and I feel like freshman in high school again. You know nothing John Snow!

Lol. I save the commit hashes for every project I do that involves HF transformers. You never know when you need to reproduce results. Even now they added new parameters to modelling llama breaking all the old training code.

**Comment by JohanAR** [comment]
@turboderp whitespace stuff like this you mean?

Prompt
```
<|im_start|>system
<|im_end|>
<|im_start|>user
Input<|im_end|>
<|im_start|>assistant
```

With HF tokenizer.. Feels like a newline after im_end is missing
```
1      -  '<s>'
32001  -  '<|im_start|>'
1587   -  'system'
13     -  '\n'
32000  -  '<|im_end|>'
32001  -  '<|im_start|>'
2188   -  'user'
13     -  '\n'
3104   -  'Input'
32000  -  '<|im_end|>'
32001  -  '<|im_start|>'
13892  -  'assistant'
13     -  '\n'
```

With exllamav2 0.0.5
```
1      -  '<s>'
32001  -  '<|im_start|>'
1587   -  'system'
13     -  '\n'
32000  -  '<|im_end|>'
28705  -  ''
13     -  '\n'
32001  -  '<|im_start|>'
2188   -  'user'
13     -  '\n'
3104   -  'Input'
32000  -  '<|im_end|>'
28705  -  ''
13     -  '\n'
32001  -  '<|im_start|>'
13892  -  'assistant'
13     -  '\n'
```

**Comment by turboderp** [comment]
It might have to do with this, from `tokenizer_config.json`:

```json
    "32000": {
      "content": "<|im_end|>",
      "lstrip": false,
      "normalized": false,
      "rstrip": false,
      "single_word": false,
      "special": true
    },
    "32001": {
      "content": "<|im_start|>",
      "lstrip": true,
      "normalized": false,
      "rstrip": true,
      "single_word": false,
      "special": true
    }
```

Maybe "lstrip" means I should be stripping any whitespace to the left of the start token?

**Comment by JohanAR** [comment]
Sounds like a good guess.. Could this be the relevant code from Transformers?

```
        # ["This is something", "<special_token_1>", "  else"]
        for i, token in enumerate(tokens):
            if token in no_split_token:
                tok_extended = self._added_tokens_decoder.get(self._added_tokens_encoder[token], None)
                left = tokens[i - 1] if i > 0 else None
                right = tokens[i + 1] if i < len(tokens) - 1 else None
                if isinstance(tok_extended, AddedToken):
                    if tok_extended.rstrip and right:
                        # A bit counter-intuitive but we strip the left of the string
                        # since tok_extended.rstrip means the special token is eating all white spaces on its right
                        tokens[i + 1] = right.lstrip()
                    # Strip white spaces on the left
                    if tok_extended.lstrip and left:
                        tokens[i - 1] = left.rstrip()  # Opposite here
                    if tok_extended.single_word and left and left[-1] != " ":
                        tokens[i - 1] += token
                        tokens[i] = ""
                    elif tok_extended.single_word and right and right[0] != " ":
                        tokens[i + 1] = token + tokens[i + 1]
                        tokens[i] = ""
```

https://github.com/huggingface/transformers/blob/21dc5859421cf0d7d82d374b10f533611745a8c5/src/transformers/tokenization_utils.py#L585

**Comment by grimulkan** [comment]
https://github.com/oobabooga/text-generation-webui/commit/1d5a015ce778270968e01adb6a30a99c6b431f76 now supports special tokens with exllamav2, finally :) I actually just noticed they never enabled it for v1!
