### ISSUE TITLE
Running Latest exllamav2 on jetson

### ISSUE THREAD

**Issue by qiuqiu10** [turboderp/exllamav2#543]
I'd like to run latest exllamav2, which is 0.1.6 version, on jetson machine. Since I haven't found existed image for this version, I had to install the environment by myself. However exllamav2 supports avx and jetson is of arm structure, I am not sure if i can delete all the avx implementation and still achieves the best performance

**Comment by turboderp** [comment]
I've only made x86 wheels, and I've only tested on x86, but it should be able to switch to non-AVX2 functions at runtime. Is it that it doesn't compile on Arm?

In any case, the AVX2 functions speed up sampling a little bit, especially for models with large vocabularies, but they're not essential.

**Comment by qiuqiu10** [comment]
thx , i'v switched off all the avx-relevant code and it can indeed work on arm structure. Maybe i will do a little test in the future to see if it works well
