### ISSUE TITLE
Parallelized inference for a batch across multiple GPUs?

### ISSUE THREAD

**Issue by rexdouglass** [turboderp/exllamav2#544]
Is there a way to use any of the existing generators to distribute a batch of string completions to multiple available GPUs, each with the same small LLM loaded independently on each?

Apologies if I've missed the documentation, I can of course load a larger LLM across multiple GPUs and see them both crank up memory and GPU usage when making an inference. But I have a simpler case where I just want to divide an conquer a batch inference with the same small LLM loaded on each card individually. When I expose multiple GPUs, the small model and inference only ever perform on just one.

**Comment by turboderp** [comment]
There is no support for this in the existing generators. Each generator can only reference a single model instance. But what you want in this case is probably multiprocessing. You'll want each model in its own process to avoid having to run each generator in turn (or GIL-related inefficiencies, not that multithreading is really supported either).

Maybe something like this, to get you started.

```python
import torch.multiprocessing as mp

def worker(index):

    # Get GPU split from index
    gs = [0, 0, 0, 0]
    gs[index] = 24

    # Alternatively:
    # gs = None
    # os.environ["CUDA_VISIBLE_DEVICES"] = ["0", "1", "2", "3"][index]

    # Import exllamav2 within each worker
    from exllamav2 import ExLlamaV2, ExLlamaV2Config, ExLlamaV2Cache, ExLlamaV2Tokenizer, Timer
    from exllamav2.generator import ExLlamaV2DynamicGenerator

    # Load model etc.
    print("Loading:", index)
    model_dir = "/mnt/str/models/llama3-8b"
    config = ExLlamaV2Config(model_dir)
    model = ExLlamaV2(config)
    model.load(gpu_split = gs)
    cache = ExLlamaV2Cache(model, max_seq_len = 1024*45)
    tokenizer = ExLlamaV2Tokenizer(config)
    print("Loaded:", index)

    # Do a single test generation in each process
    generator = ExLlamaV2DynamicGenerator(
        model = model,
        cache = cache,
        tokenizer = tokenizer,
    )
    prompt = "Once upon a time,"
    output = generator.generate(prompt = prompt, max_new_tokens = 150, add_bos = True)
    print("----------->", index)
    print(output)

if __name__ == "__main__":

    # Required
    mp.set_start_method("spawn")

    # Launch processes
    processes = []
    num_workers = 4
    for i in range(0, num_workers):
        p = mp.Process(target = worker, args = (i,))
        processes.append(p)
        p.start()

    # Wait for all processes to end
    for p in processes:
        p.join()
```

You'll then want to have some mechanism in the main process to split batches, distribute them into the subprocesses and collect the outputs.

**Comment by rexdouglass** [comment]
Excellent. Thank you for the quick and thorough response (and for the awesome library).
