### ISSUE TITLE
Prefill not done

### ISSUE THREAD

**Issue by qiuqiu10** [turboderp/exllamav2#553]
Hello, I'm new to this project and want to test the speed of prefilling. I'm currently using examples/inference.py but found out that the prefill stage did not actually generate any tokens. I'm confused, is it I need to change something to get the prefill going? (For example I want to prefill 100 tokens with the prompt 'Once upon a time')

**Comment by DocShotgun** [comment]
"Prefilling" is the part of the process during which the prompt is ingested, prior to the first token being generated. So it is normal for it to not generate any tokens.
