### ISSUE TITLE
Problem with async-generator 

### ISSUE THREAD

**Issue by balu54** [turboderp/exllamav2#561]
# Receiving irrelevant responses from the model while making parallel calls.
#  The code 
```
    async def create_generator(
         self, model, tokenizer, cache, settings, streamer=False
    ):
    prompt_format = prompt_formats[settings.mode]()
    generator = AsyncGenerator(
        model=model,
        cache=cache,
        tokenizer=tokenizer,
    )
    return generator, prompt_format

async def inference(self, collection, batch):
    global count
    llm, prompt_format = await self.create_generator(**vars(collection))
    try:
        async def run_job(prompt: str, marker: str):
            job = AsyncJob(
                llm,
                prompt=prompt,
                input_ids=llm.generator.tokenizer.encode(
                    prompt, add_bos=False
                ),
                return_last_results=True,
                stop_conditions=[
                    llm.generator.tokenizer.eos_token_id, "",
                    ""
                ],
                max_new_tokens=200
            )

            full_completion = ""
            try:
                async for result in job:
                    full_completion += result.get("text", "")
                    print(marker, end=" ")
                    sys.stdout.flush()
            except Exception as exc:
                pass
            return full_completion

        count += 1
        if isinstance(batch, dict):
            output = await run_job(
                await self.format_prompt(batch["messages"], prompt_format),
                count
            )
        else:
            tasks = [
                run_job(
                    await self.format_prompt(kwargs["messages"], prompt_format), count + i
                ) for i, kwargs in enumerate(batch)
            ]
            outputs = await asyncio.gather(*tasks)
            count += len(batch)

            outputs = get_completion_format(outputs, llm)
            return outputs  
```

The problem is that when I gave a single call to do inference, it worked perfectly and produced excellent results. However, if I made a call while the generation was in process, the new call would also have the context of the ongoing call. Example, when I hello as single call it say hello how can I assist u. But when i ask hello and what is ur name (2 different calls).
The responses are like

![IMG_20240721_234917](https://github.com/user-attachments/assets/efa4055a-0044-4e67-8d94-123970159dbe)

I checked the input prompts, and they are formatted correctly. Can you provide a solution for this?

**Comment by turboderp** [comment]
I'm not really following the code there. Are you creating a generator for each job?

**Comment by balu54** [comment]
> I'm not really following the code there. Are you creating a generator for each job?


Yes bro,

**Comment by turboderp** [comment]
It's essential to only have one generator per model, though. That's the place where multiple concurrent requests are batched together. If you create multiple generators with the same cache you won't have any benefits from batching, and more importantly you'll have two separate tasks overwriting the same memory.

Basically you want to create model+cache+tokenizer+generator once, and after that you can create as many async jobs as you want referencing the same generator. They'll function as iterable objects that you can pull your completions from, with batching and deduplication handled transparently by the underlying generator.

**Comment by turboderp** [comment]
The filters *should* be reusable, but probably you don't want to because they're also stateful. Which means you can't use the same filter in multiple jobs at once, so you'd at least have to manage a cache of filters.

What you can do, though, is import [this function](https://github.com/noamgat/lm-format-enforcer/blob/20e0b6d0e5ddb03be8b2061a4c8866b52b4614c5/lmformatenforcer/integrations/exllamav2.py#L28) from lm-format-enforcer, then call it once to produce a single `TokenEnforcerTokenizerData` object you can reuse for all filters that use the same tokenizer. Simply pass that instead of the tokenizer to `ExLlamaV2TokenEnforcerFilter()` to skip the expensive preprocessing, and then creating new filters should be quite fast. I.e:

```python
from lmformatenforcer.integrations.exllamav2 import ExLlamaV2TokenEnforcerFilter, build_token_enforcer_tokenizer_data
from lmformatenforcer import JsonSchemaParser

...

tokenizer = ExLlamaV2Tokenizer(config)
tokenizer_lmfe_data = build_token_enforcer_tokenizer_data(tokenizer)  # reusable

...

schema_parser = JsonSchemaParser(my_schema)  # also reusable

...

job = ExLlamaV2DynamicJobAsync(
    prompt = "Blah blah..",
    ...
    filters = ExLlamaV2TokenEnforcerFilter(schema_parser, tokenizer_lmfe_data),
)
```

**Comment by balu54** [comment]
Yo bro thanks for the quick response ll try this... 💛
