### ISSUE TITLE
Unable to load gptq models

### ISSUE THREAD

**Issue by abpani** [turboderp/exllamav2#563]
Error while loading llama 8b gptq
# GPTQ without g_idx
    379 
    380 else:
    382     return ext_c.make_q_matrix(w["qweight"],
    383                                none_tensor,
    384                                none_tensor,
   (...)
    393                                temp_dq,
    394                                max_dq_rows)

RuntimeError: q_weight and gptq_qzeros have incompatible shapes

Please help.

**Comment by turboderp** [comment]
Sorry I overlooked this. There is currently no support for 8-bit GPTQ models. Only 4-bit is supported. There will be more modes added at some point.

**Comment by abpani** [comment]
close
