### ISSUE TITLE
Enhancement: Docker Image Github Actions

### ISSUE THREAD

**Issue by 0x4139** [turboderp/exllamav2#570]
I propose adding GitHub Actions workflows to automate the building of Docker images for multiple architectures (e.g., x86, ARM). This enhancement will streamline the development process, ensure cross-platform compatibility, and improve our CI/CD pipeline.

## Benefits

1. **Cross-Platform Compatibility**: Support diverse deployment environments, including cloud, on-premises, and edge devices.
2. **Consistency and Reliability**: Automated builds reduce human error and maintain consistent build conditions.
3. **Improved CI/CD Pipeline**: Faster delivery of updates and new features through continuous integration and deployment.
4. **Community Support**: Simplifies testing and deployment for contributors, encouraging more contributions.
5. **Future-Proofing**: Adapts to evolving hardware landscapes by supporting multiple architectures.

## Proposed Implementation

1. **GitHub Actions Workflow**: Create a workflow file (`.github/workflows/docker-build.yml`) to define multi-architecture build steps.
2. **Docker Buildx**: Use Docker Buildx for building and pushing multi-platform images.
3. **Supported Architectures**: Target architectures like `linux/amd64` and `linux/arm64`.
4. **Publishing**: Publish images to Docker Hub or Github Container REgistry.

Feel free to reach out for any clarifications or further discussions.
I am open to submitting a pull request.

**Comment by turboderp** [comment]
I'm not opposed to this, I just have little I could personally contribute to it. I don't use Docker myself and find it (and other packaging solutions) more of a hindrance than anything else, at least for the local inference the project is meant to be focused on.
