### ISSUE TITLE
A doubt regarding filters/tools.

### ISSUE THREAD

**Issue by royallavanya140** [turboderp/exllamav2#581]
The filters we are using in this exllamav2 are the same as the tools in OpenAI, right?

I  convert the openai tools schema as pydantic schema (schema supported by exlllamav2). but the response are not at all same.

i used this in autogen for agentic response.

this is the result when i used exllamav2
![image](https://github.com/user-attachments/assets/e57ccfdd-b939-481c-863f-b61067687626)

this is result when i use dummy openai base URL (llamacpp-python)
![image](https://github.com/user-attachments/assets/1e2007e3-c1dc-4a58-b29f-cedb3ade3f84)

**Comment by royallavanya140** [comment]
Schema used to create filter/tool in this example: 

```json

{"description": "A simple calculator",
 "properties": {"a": {"type": "integer", "description": "a"},
  "b": {"type": "integer", "description": "b"},
  "operator": {"enum": ["+", "-", "*", "/"],
   "type": "string",
   "description": "operator"}},
 "required": ["a", "b", "operator"],
 "type": "object",
 "title": "calculator"}
```

**Comment by royallavanya140** [comment]
When can we expect OpenAI-supported API hosting from exllamav2? :)

**Comment by turboderp** [comment]
Not familiar with the framework you're using there, but it looks like the exllamav2 instance is just being asked to use a JSON filter, which isn't how tools are meant to work. The model is supposed to decide when to make the tool call, not simply use the tool schema for its entire response.

By contrast the lcpp response makes no use of the schema at all, so I'm not sure what you're expecting to happen there?

I would check out TabbyAPI for the current situation regarding [this PR](https://github.com/theroyallab/tabbyAPI/pull/154).
