### ISSUE TITLE
Exllama v2 crashes when starting to load model in the third gpu

### ISSUE THREAD

**Issue by ciprianveg** [turboderp/exllamav2#583]
Exllama v2 crashes when starting to load in the third gpu. No matter if the order is 3090,3090,A4000 or A4000,3090,3090, when I try to load the turboderp Mistral Large 2407 exl2 3.0bpw it crashes after filling the first 2 gpus and when it should start loading the rest of the model in the third gpu. There are 64gb vram so it should work fine. Loading the model as gguf is working with llams.cpp, but I prefer exl2. I am using it via oobabooga and is updated to latest version..

**Comment by ciprianveg** [comment]
I tested also with turboderp llama 3.1 70b exl 6.0bpw, it also fails to load on the 3rd gpu but sometimes it doesn't completely crash and exit and when it doesnt i receive this error: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.00 GiB. GPU 2 has a total capacity of 24.00 GiB of which 22.54 GiB is free. Of the allocated memory 155.58 MiB is allocated by PyTorch, and 30.42 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.

**Comment by remichu-ai** [comment]
Can you try to load the model directly and share the error? You can find the sample code to load model from the examples folder in this repo.

For mistral large one thing is it has huge context of 128k, and if the context and cache is fully initialised to 128k, you might not have enough vram as you think. On my pc of 84GB VRam, i can only load the model at 4bpw with reduced context.

**Comment by ciprianveg** [comment]
The context was set to 8000. As I wrote in my second comment, same thing happened with llama 3.1 but here i could get an error message: I tested also with turboderp llama 3.1 70b exl 6.0bpw, it also fails to load on the 3rd gpu but sometimes it doesn't completely crash and exit and when it doesnt i receive this error: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.00 GiB. GPU 2 has a total capacity of 24.00 GiB of which 22.54 GiB is free. Of the allocated memory 155.58 MiB is allocated by PyTorch, and 30.42 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.

**Comment by grimulkan** [comment]
Not sure if it is the same error, but I can replicate very similar situations. It always crashes when loading a shard onto a new GPU. It doesn't seem to be related to the actual VRAM size, and it happens whether I use the fasttensors loading process or not.

You need to have > 2 GPUs to get it to happen.

Egs., when loading a 6bit 405B model, it crashes when loading on the 3rd or 4th GPU. But if I fiddle with the gpu_split options, it loads just fine. At no point am I close to the VRAM limit of any GPU. Sometimes increasing gpu_split memory per GPU helps, sometimes it needs to be reduced.

The same gpu_split allocation may fail for the 3bit version of the same model for instance.

In all cases, the crash is a reported out of memory error, when trying to create a tensor on a completely empty GPU.

**Comment by ciprianveg** [comment]
In 2 gpus all is fine in my tests, with 3 gpus the problem appears..

**Comment by grimulkan** [comment]
I can post my command but its probably not easily replicable since it is a large model with many GPUs. I too cannot re-create the problem with only 2 GPUs.

For example (8 GPUs):
```
python test_inference.py ek826_Meta-Llama-3.1-405B-Instruct-4.0bpw-exl2 -gs 46,45,45,45,45,45,45,48 -fst <other options>
```

The failure is in either `get_tensor()` in `fastensors.py` or `safetensors_read_fb()`, depending on whether `-fst` option was used or not. Sometimes it gets past this line, but fails in the very next tensor allocation.

The failure is always when starting to load a layer on a new GPU, after hitting the mem limit on the previous GPU, and usually does not happen in the first 2 GPUs (though that may be luck).

@ciprianveg is this the same pattern for you? If not, maybe I should make a separate issue, but it sounded exactly like what you described.

I've tried GPUs connected straight to PCIe slots, as well as via re-timers, it doesn't seem to be the problem. The whole thing is repeatable for a given set of settings usually, but changing the model itself sometimes does not trigger the problem. Example, the above loading pattern works perfectly fine on a 6-bit model.

At first I suspected VRAM fragmentation, but there is plenty of VRAM available on the new GPU. If I reduce the VRAM limit in the `-gs` option for all GPUs (while stilling leaving enough to load all the weights, scratch, etc.), that ensures there is also plenty of VRAM left in the previous GPU, so I don't think it's an OOM on the previous GPU either.

**Comment by ciprianveg** [comment]
Hi, yes, it is the same for me, for 2 gpus it never happens, and I noticed that a small enough model that can fit in 2gpus can be split in 3 gpus, but a larger model that needs more than the capacity of the first 2gpus, even if it needs just 2gb from the 24 gb of the 3rd gpu, crashes when starting to load on third gpu.. And it is not hardware related since same or bigger gguf are loading in vram only without  spill on ram..

**Comment by ciprianveg** [comment]
@remichu-ai can you please remove or disable a gpu to have 3 gpus?

**Comment by ciprianveg** [comment]
Thank you. I will try with your drivers version, windows? Can you tell me the settings you used, please? Or auto-split?

**Comment by ciprianveg** [comment]
hello again, installing older windows nvidia drivers fixed my issue: nvidia 545.92

**Comment by grimulkan** [comment]
Rats, I think that's the last version before they patched shared mem fallback. I'd hate for that to be the issue again... Trying...

**Comment by grimulkan** [comment]
I can confirm, that with NO driver changes (including the latest driver), setting all GPUs to WDDM mode fixes the problem.

@ciprianveg Your A4000 is a TCC mode GPU (assuming you are on Windows), right? But your other GPUs are WDDM? I also have some TCC mode GPUs. Trying to narrow it down.

I will try the older drivers in TCC mode. Sysmem fallback should not be affecting TCC mode, but there are so many bugs with TCC mode in Windows NVidia probably never tested it...

**Comment by ciprianveg** [comment]
![image](https://github.com/user-attachments/assets/3bf756ad-9c0e-4ab5-9c02-689175e4c6f9)
I see all are working in WDDM mode by default with this old driver

**Comment by ciprianveg** [comment]
@grimulkan I confirm that with latest drivers, with all set on WDDM it is working, so it looks like on newer drivers TCC has some issues. Thank you all!

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.70                 Driver Version: 560.70         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090      WDDM  |   00000000:04:00.0 Off |                  N/A |
| 47%   45C    P8             13W /  234W |       0MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA RTX A4000             WDDM  |   00000000:05:00.0 Off |                  Off |
| 49%   51C    P8              7W /  140W |       0MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA GeForce RTX 3090      WDDM  |   00000000:07:00.0  On |                  N/A |
| 42%   49C    P0            105W /  247W |     190MiB /  24576MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

**Comment by grimulkan** [comment]
Okay, thanks for checking. It might not be related to sysmem fallback: yes, they patched that right after 545.xx, but I recall they also fixed P2P (was being falsely reported as being available and was broken when used) and mixed TCC/WDDM mode (would cause Nvidia control panel to crash/not show up). So staying on 545.xx is not really an option.

Nvidia simply does not care enough about Quadro or TCC mode in Windows anymore I think, so who knows if/when they will ever fix this. If anyone knows of a good place to report this to NVidia, please tell.

But either way, not an exllama problem anymore :)
