### ISSUE TITLE
Stream Bug

### ISSUE THREAD

**Issue by wangyu1997** [turboderp/exllamav2#59]
<img width="702" alt="image" src="https://github.com/turboderp/exllamav2/assets/15991233/4445a06b-20c3-480a-83b0-2e4a15ec6686">

The model will ouput $ sometimes when using stream infer

**Comment by turboderp** [comment]
Could you be more specific about the model and the prompt, and how you're using the streaming generator? I can't really parse that output.

**Comment by wangyu1997** [comment]
The model we use is based on the LLaMa2 fine-tuned Chinese large model: [https://huggingface.co/TigerResearch/tigerbot-70b-chat-4bit-exl2](Tigerbot-70B-Chat).

When using infer to generate the text at one time, there is no `$`  in the generated text. 

However, when using stream, the model may experience lag during generation, resulting in the generation of `$` and affecting subsequent text. I found out after debugging that it was in the `streaming.gen_ single_token `

The problem with tokens is that it may sample `$` when sampling. 

Currently, we do not know the reason for this.


![image](https://github.com/turboderp/exllamav2/assets/15991233/6f48c0da-db1d-47e5-adf1-4279467432c5)

The prompts is: `请你帮我全文默写长恨歌`

**Comment by wangyu1997** [comment]
There is another issue. 

During the process of using stream, some traditional Chinese characters are represented by two tokens. 

For example, the encoding for "阳鼙鼓动地来" is `[31430, 236, 191, 156, 55373, 30846, 30533, 30805]`. 

However, when outputting one token at a time, it may result in garbled characters.

![image](https://github.com/turboderp/exllamav2/assets/15991233/3775135b-9d48-4d80-9699-5a4146e4e0f6)

![image](https://github.com/turboderp/exllamav2/assets/15991233/fa843b29-e537-4dca-a12b-77f2a3135bcc)

![image](https://github.com/turboderp/exllamav2/assets/15991233/5d273bf4-1025-427f-89d6-f8748697aef5)
