### ISSUE TITLE
will it be possible to make something like this for diffusion?

### ISSUE THREAD

**Issue by Shaistrong** [turboderp/exllamav2#60]
the strongest optimization for diffusion almost doubles the speed while exLLaMa multiplies it by 9.. I tested exLLaMa and it went from 8T/s with autoGPTQ to 62IT/s with exLLaMav2.

**Comment by bkutasi** [comment]
You mean writing specifically optimised kernels for Stable Diffusion? The best you can get is [VoltaML-Fast-SD](https://github.com/VoltaML/voltaML-fast-stable-diffusion). Depending on your hw and settings you might get 7x speedup, but if you are used to ComfyUI the speedup is less. But as far as i know they are not using specific optimised kernels for this.

**Comment by Shaistrong** [comment]
> You mean writing specifically optimised kernels for Stable Diffusion? The best you can get is [VoltaML-Fast-SD](https://github.com/VoltaML/voltaML-fast-stable-diffusion). Depending on your hw and settings you might get 7x speedup, but if you are used to ComfyUI the speedup is less. But as far as i know they are not using specific optimised kernels for this.

AIT is also available for ComfyUI and only doubles speed, not even close to the speedups exLLaMa can do
