### ISSUE TITLE
Pipeline mode support

### ISSUE THREAD

**Issue by laoda513** [turboderp/exllamav2#605]
I found that torch2.4 officially supports Pipeline Parallelism, the package name is torch.distributed.pipelining。 It was migrated from the [PiPPy](https://github.com/pytorch/PiPPy) project.

Will exllamav2 add support for Pipeline Parallelism sometime?

**Comment by turboderp** [comment]
Possibly, but not before fully exploring tensor parallelism which potentially makes PP totally redundant. I.e. why run two staggered batches at 1x speed when you can run a single batch at 2x speed?

**Comment by laoda513** [comment]
TP have high communication requirements, so the performance improvement for PCIe devices might not be as significant as expected. On the other hand, PP has lower communication requirements, theoretically leading to a larger performance boost. 

However, PP doesn't seem to be very useful for single-batch inference. 😂😂😂
