### ISSUE TITLE
[REQUEST] need exllamav2-0.2.1+cu121.torch2.4.0-cp310-cp310-win_amd64.whl

### ISSUE THREAD

**Issue by dancemanUK** [turboderp/exllamav2#624]
### OS

Windows

### GPU Library

CUDA 12.x

### Python version

3.10

### Pytorch version

torch 2.41.

### Describe the bug

[REQUEST] need exllamav2-0.2.1+cu121.torch2.4.0-cp310-cp310-win_amd64.whl

Recently, I have been using Comfyui and Flux models to improve generation speed. Upgrade to torch 2.41. Now (Import Failed): ComfyUI \ custom_nodes \ ComfyUI ExLlama

Thank you!

### Reproduction steps

[REQUEST] need exllamav2-0.2.1+cu121.torch2.4.0-cp310-cp310-win_amd64.whl

Recently, I have been using Comfyui and Flux models to improve generation speed. Upgrade to torch 2.41. Now (Import Failed): ComfyUI \ custom_nodes \ ComfyUI ExLlama

Thank you!

### Expected behavior

[REQUEST] need exllamav2-0.2.1+cu121.torch2.4.0-cp310-cp310-win_amd64.whl

Recently, I have been using Comfyui and Flux models to improve generation speed. Upgrade to torch 2.41. Now (Import Failed): ComfyUI \ custom_nodes \ ComfyUI ExLlama

Thank you!

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by turboderp** [comment]
Should be in the wheels for the latest release.
