### ISSUE TITLE
[BUG] exllamav2-0.2.2+cu118.torch2.4.0-cp310-cp310-win_amd64.whl Version seems missing under releases.

### ISSUE THREAD

**Issue by Nrgte** [turboderp/exllamav2#633]
### OS

Windows

### GPU Library

CUDA 11.8

### Python version

3.10

### Pytorch version

2.4.0

### Describe the bug

whl for windows 3.10 is missing.

### Reproduction steps

-

### Expected behavior

-

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by turboderp** [comment]
This is added now and should be compiled for 0.2.3+
