### ISSUE TITLE
[REQUEST] Implement Transformer's YaRN Scaling for Long Context in Supported Models (e.g. Qwen 2.5)

### ISSUE THREAD

**Issue by Downtown-Case** [turboderp/exllamav2#641]
### Problem

Some models (like Qwen 2.5's Instruct models) are specifically trained for long context usage with a technique called [YaRN](https://arxiv.org/abs/2309.00071). Exllamav2 doesn't support this, which means it's limited to whatever the base context of the model is.

### Solution

Implement HF Transformer's implementation of YaRN.

### Alternatives

Not every model supports YaRN, and one could simply use a model that doesn't.

But Qwen 2.5's release feels hugely significant, and I'm not even aware of an implementation that supports YaRN other than vanilla transformers... and _maybe_ llama.cpp? But most llama.cpp front ends don't expose it, and I've never even seen it used in the wild other than om one offhand Reddit comment that mentions its not quite right.

Qwen's own documentation mentions that vllm only supports static scaling factors, which degrades performance at anything but the target context.

### Explanation

This feature should be added to support longer context on models trained with YaRN. 

### Examples

Transformer's implementation of YaRN scaling seems to be here: https://github.com/huggingface/transformers/blob/2e24ee4dfa39cc0bc264b89edbccc373c8337086/src/transformers/modeling_rope_utils.py#L163

Here is an example of a significant model that requires YaRN for >32K context: https://huggingface.co/Qwen/Qwen2.5-32B-Instruct#processing-long-texts

> For supported frameworks, you could add the following to `config.json` to enable YaRN:

```json
{
  ...,
  "rope_scaling": {
    "factor": 4.0,
    "original_max_position_embeddings": 32768,
    "type": "yarn"
  }
}
```

### Additional context

It seems that YaRN isn't going away anytime soon, and this feature could be used for other models in the future. A huggingface blog post claims their experiments with  Infini-Attention didn't pan out, and to quote them:

> Unfortunately, despite these progress, we found that Infini-attention was not convincing enough in our experiments and in particular not reliable enough. At this stage of our reproduction we are still of the opinion that Ring Attention [[link]](https://x.com/Haojun_Zhao14/status/1815419356408336738), YaRN [[link]](https://arxiv.org/abs/2309.00071) and rope scaling [[link]](https://arxiv.org/abs/2309.16039) are better options for extending a pretrained model to longer context length.

I suppose more models could switch to a hybrid transformers-mamba2 architecture like Jamba or Nvidia's models without having to "resort" to YaRN , but that hasn't panned out yet, and its outside exllama's wheelhouse: https://arxiv.org/abs/2406.07887

Qwen staff also confirmed that their instruct models are _specifically_ trained to support YaRN: https://huggingface.co/Qwen/Qwen2.5-32B/discussions/1#66f11ee85a65f26be709470b

### Acknowledgements

- [X] I have looked for similar requests before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will make my requests politely.

**Comment by turboderp** [comment]
I'm a little confused too. None of the Qwen models seem to define YaRN in their configs. I tested your PR with a Mistral model finetuned for YaRN, and it seems to behave somewhat?

![image](https://github.com/user-attachments/assets/b333b973-e06d-48b0-95a2-9dce21b74208)

As soon as YaRN is enabled there's an increase in perplexity, and it breaks down at various points depending on the max_seq_len set. Interestingly 32k performs best up to 32k, while going any higher than causes the model to start to break down *before* 32k.

I tested Qwen2.5-14B Instruct as well:

![image](https://github.com/user-attachments/assets/9d71fce0-e647-49de-9792-bf72a1596294)

This suggests there's no reason you'd want to use YaRN with Qwen2.5 since it performs strictly worse up to 128k. Possibly perplexity just isn't the right benchmark for this. Maybe the long-context tuning specifically relates to the instruct mode in a way that isn't captured at all by wikitext.

So I'm not sure. The PR seems to do what it's supposed to, but is there a better way to test it to actually measure an improvement?

**Comment by Lissanro** [comment]
I think one of the best tests for long context is https://github.com/hsiehjackson/RULER - it can expose issues that neither perplexity nor niddle-in-a-haystack tests do not. Perplexity can be somewhat useful too, but slight increase followed by further increase is to be expected when trying to extend the context length. The fact that a model fine-tuned for 128K behaves the best at 32K is also quite typical, and seems to be widespread across many models according to the RULER test. Usually there is always a build up of degradation in quality as we approach the max context size.

That said, I am not YaRN expert, so maybe I am missing something. But I think RULER is one of the best ways currently to check if there is an actual improvement in effective context length, if I correctly understood the question about measuring an actual improvement.

**Comment by Downtown-Case** [comment]
It makes a massive difference for Qwen 32B at like 80K. No Yarn is looping incoherent english, Yarn makes it behave normally.

I think perplexity is problematic as long context metrics, as I noticed base Qwen 32B is horrible at long context, even though the trainers claim its perplexity is fine:

> The context length of the base model is determined by evaluation through perplexity (ppl). We did not observe significant ppl degradation at 128k context length. However, this does not imply that the base model can generate coherent content at such long contexts. We recommend using the instruct model for generation tasks.

> If you use YARN on the base model, you should also achieve better long-text results, but coherence between different parts of the text still isn't guaranteed since the model hasn't been trained for that.

https://huggingface.co/Qwen/Qwen2.5-32B/discussions/1

@turboderp My plan is to test this with infinibench, as it has a TabbyAPI endpoint. Just haven't gotten around to setting it up this weekend: https://github.com/OpenBMB/InfiniteBench/blob/main/src/eval_multi_api.py

**Comment by Downtown-Case** [comment]
> None of the Qwen models seem to define YaRN in their configs.

Oh, and they deliberately leave it out for users to paste in, see: https://huggingface.co/Qwen/Qwen2.5-14B-Instruct#processing-long-texts

And why? I think it's ergonomics for vllm, as it enables YaRN at 128K by default, which many "regular" vllm users wouldn't want since it eats memory and degrades lower context performance in vllm's implementation.
