### ISSUE TITLE
[BUG] Qwen 2.5 32B quantization produces artifact at any level

### ISSUE THREAD

**Issue by Nepherpitou** [turboderp/exllamav2#644]
### OS

Windows

### GPU Library

CUDA 12.x

### Python version

3.12

### Pytorch version

2.4.0+cu121

### Model

Qwen/Qwen2.5-32B-Instruct

### Describe the bug

Whatever quantization level (from 3.5 up to 4.6 bpw) I'm using for this model (or it's abliterated version), I've always got artifacts like ? unicode symbols or chinese letters. But it's never happening with GGUF Q3 version and above.
I've tryed to change calibration data, to use same calibration as used for GGUF imatrix from Bartowski gist file, but it's 100% reproduceable from run to run.
I'm usning TabbyAPI to run inference and both master and dev branches to run quantization.

Upd: After some investigation I've found it's tokenizer issue, not the model itself. But due to incorrect tokenization this model produces incoherent outputs. Not sure if it's true for english only strings (highly likely not), but it's zeroed it's multilangual abilities.

### Use TabbyAPI
1. Load any Qwen 2.5 32B quant
2. Try chat completition with ask for word "доработка" (russian word "improvement"), occasionly found this issue with this particular word, but looks like it indication of bigger issue.
```
POST http://{host}/v1/chat/completions
Authorization: Bearer token
Content-Type: application/json

{
  "messages": [
    {"role": "user", "content": "Напиши слово \"доработка\""}
  ],
  "stream": false
}
```
3. Response will contain "Дора��отка". It's not an encoding or charset issue.

### Tokenizer
Decoded string will not match encoded one.
```python
print(
  tokenizer.decode(
    tokenizer.encode("доработка")
  )
)
```

### TabbyAPI
Response must contain "доработка" or, at least, must not contain special unicode characters.

### Tokenizer
encode -> decode sequence must return initial value

### Additional context

Sorry, I can't provide more details since I'm too newbie and don't know how to debug or fix this bug, or is this a bug at all.
But I'll help you with everything I can if you provide actionable steps I can follow up.

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by turboderp** [comment]
Thanks for the detailed report.

In all other tokenizer models I've come across, an incomplete character always ends in `�` when decoded and the next token after that is always an incomplete character as well. And Qwen seems to break that pattern. ` доработка` breaks down to ` дор` + `а�` + `�от` + `ка`, with `б` spanning a token boundary in between complete characters.

I'm not sure why Qwen is different in this regard, but I think the latest commit to the dev branch should fix it by correctly re-decoding sequences if they contain replacement characters anywhere. Seems okay now:

![image](https://github.com/user-attachments/assets/8796b47a-b641-4f67-840e-26af6f56d8c0)

**Comment by Nepherpitou** [comment]
Man, you're awesome. I've built wheel for TabbyAPI and it works great! I'm finally able to use Qwen 2.5 with 24Gb VRAM without issues.
```json
{
  "id": "chatcmpl-ed8bfc1c85f9402a97f2cf99946baa1b",
  "choices": [
    {
      "index": 0,
      "finish_reason": "stop",
      "stop_str": "<|im_end|>",
      "message": {
        "role": "assistant",
        "content": "доработка",
        "tool_calls": null
      },
      "logprobs": null
    }
  ],
  "created": 1727593064,
  "model": "qwen2.5-32b-agi-4.6bpw",
  "object": "chat.completion",
  "usage": {
    "prompt_tokens": 36,
    "completion_tokens": 3,
    "total_tokens": 39
  }
}
```
