### ISSUE TITLE
[REQUEST] create the output directory during the quantization process

### ISSUE THREAD

**Issue by Nexesenex** [turboderp/exllamav2#653]
### Problem

The output directory is not created automatically on Windows 11, and it crashes the quantization process.

Ex :

Q:\GitHub\exllamav2.fks>convert.py -i E:\text-generation-webui\models\mlx-community_Mistral-Large-Instruct-2407-bf16 -o D:\text-generation-webui\models\Mistral-Large-Instruct-2407-EXO2 -cf X:\text-generation-webui\models\Mistral-Large-Instruct-2407-3.9bpw-h6-exl2 -m Q:\measurements\Mistral_Large_DbMe_measurements.json -b 3.9 -hb 6

 ## Error: Directory not found: D:\text-generation-webui\models\Mistral-Large-Instruct-2407-EXO2

### Solution

Unless I made a mistake, could it be created by the script instead please?

### Explanation

Simple convenience, to not create it manually because I'm using several ones.

### Acknowledgements

- [X] I have looked for similar requests before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will make my requests politely.

**Comment by iamwavecut** [comment]
I encounter this a lot, too, so proposed this little PR to resolve this issue.

**Comment by turboderp** [comment]
Merged into dev now. :+1:
