### ISSUE TITLE
[BUG] Async with Paged Attention Reduces accuracy

### ISSUE THREAD

**Issue by rjmehta1993** [turboderp/exllamav2#676]
### OS

Linux

### GPU Library

CUDA 12.x

### Python version

3.10

### Pytorch version

2.5.0

### Describe the bug

Async with paged attention reduces the accuracy when compared to running the same prompt without async and processing one request at a time.

I ran a rag test with 8000 context length on Qwen 2.5 32b 8bpw with async + paged attention AND without async and no paged attention.

Below are the results:

Total questions: 500
No Paged_No_Asyn (Correct/Hits): 82.19999999999999 %
No_Paged_No_Asyn (InCorrect/Miss): 17.8 %
Paged_With_Asyn (Correct/Hits): 69.19999999999999 %
Paged_With_Asyn (InCorrect/Miss): 30.8 %
Paged_With_Asyn_Correct AND No_Paged_No_Asyn INCORRECT: 4.3999999999999995 %
Paged_With_Asyn_Correct INCORRECT AND No_Paged_No_Asyn CORRECT: 17.4 %

Sample response with paged+async AND nopage+noasync

```
QUESTION: Does the document mention that some obligations of the Agreement may survive the termination of the Agreement?
----------------------
TRUE ANSWER: 2. Upon the termination of this Agreement for any reason, the confidentiality provisions set forth herein shall continue to apply to the Data shared with Data Recipient pursuant to this Agreement. 
----------------------
RESPONSE No_Paged_No_Async: Yes, the Data Use Agreement in New York City does mention that some obligations of the Agreement may survive the termination of the Agreement. Specifically, Section D. Effect of Termination, paragraph 2 states that "Upon the termination of this Agreement for any reason, the confidentiality provisions set forth herein shall continue to apply to the Data shared with Data Recipient pursuant to this Agreement." Additionally, Section V. CONFIDENTIALITY AND SECURITY OF DATA, paragraph G. Survival, clarifies that "Upon the Expiration of this Agreement, only the continued use of Data for the purposes set forth in Attachment B will cease. All other provisions of this Agreement, including this Section V, shall survive." These provisions indicate that confidentiality obligations and other stipulated conditions will persist even after the Agreement's termination.
----------------------
RESPONSE Paged_With_Async:   
Yes, the document mentions that some obligations of the Agreement may survive the termination of the Agreement. Specifically, Section VI.G of the Data Use and Non-Disclosure Agreement states:

"Upon the Expiration of this Agreement, only the continued use of Data for the purposes set forth in Attachment B will cease. All other provisions of this Agreement, including this Section V, shall survive."

This indicates that the confidentiality provisions and other parts of the Agreement remain in effect even after the Agreement has expired or been terminated.
----------------------

CHATGPT EVALUATION OF EACH ANSWER: 

RESPONSE No_Paged_No_Async: CORRECT

Accurately identifies that obligations survive termination
Cites two relevant sections: Section D (Effect of Termination) and Section V.G (Survival)
Provides specific quotes from both sections
Explains that confidentiality obligations and other conditions persist after termination
Provides comprehensive and accurate information without any errors

RESPONSE Paged_With_Async: PARTIALLY CORRECT

Correctly states that obligations survive termination
Cites Section "VI.G" which is incorrect (should be V.G)
Provides accurate quote from Section V.G
Limited in scope compared to Response Single as it doesn't mention the additional relevant section about confidentiality provisions continuing to apply
Contains a citation error that could be misleading
```

**_EXAMPLE BELOW_**

### Reproduction steps

```
from exllamav2.generator import ExLlamaV2Sampler, ExLlamaV2DynamicJobAsync
from typing import Any, List, Optional, Union, TypedDict

    async def generate_data(
        self,
        prompt: str,
        tokenizer: Any,
        generator: Any,
        stop_token_ids: List[Union[int, str]]
    ) -> str:
        """Return data after generation tokens by tokens, handling any errors that arise."""

        input_ids = tokenizer.encode(prompt, add_bos=True)

        job = ExLlamaV2DynamicJobAsync(
            generator,
            input_ids=input_ids,
            max_new_tokens=self.max_tokens,
            token_healing=True,
            stop_conditions=stop_token_ids,
            gen_settings=self.settings,
        )
        async for result in job:
            text = result.get("text", "")
            if result["eos"]:
                break
            self.response += text
        return self.response

async def zendesk_chat_job(llmprocessor: LlmChatProcessor):
    start_chat = datetime.now()
    answer = await llmprocessor.generate_data(prompt, tokenizer, generator, stop_token_ids=STOP_TOKEN_IDS)
    end_chat = datetime.now()
    return answer

```

### Expected behavior

The Answer with Paged attention along with Async Generator should match the response generated without paged attention and using DynamicGenerator without async

### Additional context

Sample response with paged+async AND nopage+noasync

```
QUESTION: Does the document mention that some obligations of the Agreement may survive the termination of the Agreement?
----------------------
TRUE ANSWER: 2. Upon the termination of this Agreement for any reason, the confidentiality provisions set forth herein shall continue to apply to the Data shared with Data Recipient pursuant to this Agreement. 
----------------------
RESPONSE No_Paged_No_Async: Yes, the Data Use Agreement in New York City does mention that some obligations of the Agreement may survive the termination of the Agreement. Specifically, Section D. Effect of Termination, paragraph 2 states that "Upon the termination of this Agreement for any reason, the confidentiality provisions set forth herein shall continue to apply to the Data shared with Data Recipient pursuant to this Agreement." Additionally, Section V. CONFIDENTIALITY AND SECURITY OF DATA, paragraph G. Survival, clarifies that "Upon the Expiration of this Agreement, only the continued use of Data for the purposes set forth in Attachment B will cease. All other provisions of this Agreement, including this Section V, shall survive." These provisions indicate that confidentiality obligations and other stipulated conditions will persist even after the Agreement's termination.
----------------------
RESPONSE Paged_With_Async:   
Yes, the document mentions that some obligations of the Agreement may survive the termination of the Agreement. Specifically, Section VI.G of the Data Use and Non-Disclosure Agreement states:

"Upon the Expiration of this Agreement, only the continued use of Data for the purposes set forth in Attachment B will cease. All other provisions of this Agreement, including this Section V, shall survive."

This indicates that the confidentiality provisions and other parts of the Agreement remain in effect even after the Agreement has expired or been terminated.
----------------------

CHATGPT EVALUATION OF EACH ANSWER: 

RESPONSE No_Paged_No_Async: CORRECT

Accurately identifies that obligations survive termination
Cites two relevant sections: Section D (Effect of Termination) and Section V.G (Survival)
Provides specific quotes from both sections
Explains that confidentiality obligations and other conditions persist after termination
Provides comprehensive and accurate information without any errors

RESPONSE Paged_With_Async: PARTIALLY CORRECT

Correctly states that obligations survive termination
Cites Section "VI.G" which is incorrect (should be V.G)
Provides accurate quote from Section V.G
Limited in scope compared to Response Single as it doesn't mention the additional relevant section about confidentiality provisions continuing to apply
Contains a citation error that could be misleading
```

Another Example of GPT Evaluation:
```
Let me analyze each response against the document and the specific question asked:
The question asks: "Does the document mention that some obligations of the Agreement may survive the termination of the Agreement?"
Let's examine each response:

RESPONSE No_Paged_No_Async: CORRECT


Accurately identifies that the document mentions survival of obligations
Correctly cites Clause 12.2
Correctly explains that obligations related to Confidential Information continue after termination
Provides a direct and precise answer to the question asked


RESPONSE Paged_With_Async: INCORRECT


Incorrectly states "there is no explicit mention that some obligations of the Agreement may survive its termination"
Contradicts itself by acknowledging that Clause 12.2 states obligations regarding Confidential Information remain intact after termination
Creates an artificial distinction between "confidentiality obligations" and "other obligations" that wasn't part of the question
Overcomplicated the analysis of a straightforward question
```

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by rjmehta1993** [comment]
@turboderp Is there any drop in accuracy when using paged attention + Async?

**Comment by turboderp** [comment]
I can't imagine how the async wrapper could affect results in any way. Paged attn does use a different code path, so it's possible there's some difference there even though the results are supposed to be identical (give or take CUDA nondeterminism, but that shouldn't have a bias one way or the other).

I'm wondering how the No_Paged_No_Asyn results were produced, though. Is it possible you end up with different sampling settings?

**Comment by rjmehta1993** [comment]
I have used the same sampler settings as below, to make it as much deterministic. But that shouldn't lead to biases. 
{"temperature": 0.01, "top_k": 0, "top_p": 0.01, "typical_p": 0.1}

This is how I use the generator for No_Paged_No_Asyn:

    def non_stream_response(self, prompt):
        response = ''
        try:
            start = datetime.now()
            self.set_llm_settings({"temperature": 0.01, "top_k": 0, "top_p": 0.01, "typical_p": 0.1}) #Initialize Gen Settings
            print("PROMPT",prompt)
            with Timer() as t_single:
                response = utils.llm_inference_generator.generate(prompt = prompt,
                                                                  max_new_tokens = 2048,
                                                                  add_bos = True,
                                                                  stop_conditions = utils.STOP_TOKEN_IDS,
                                                                  gen_settings = self.settings)
            end = datetime.now()
        except Exception as err:
            logger.error(err)
        return response

**Comment by rjmehta1993** [comment]
Also, I do know that the cache size affects output if all requests consume the kv cache. Like if 1 request is running and cache max seq len is 32768, it can consume all of it. But if 100 requests are running at once, each request might have reduced cache size but the total cache for all requests will still be 32768. Could that create bias?

**Comment by DocShotgun** [comment]
> {"temperature": 0.01, "top_k": 0, "top_p": 0.01, "typical_p": 0.1}

Why not just `top_k` = 1 if you want as deterministic as CUDA non-determinism will allow?

Not that I think that's necessarily the cause here if it's the same for both tests, but a low `typical_p` does some interesting things like drop the top probability token in some scenarios.

**Comment by rjmehta1993** [comment]
@DocShotgun That is a good point. I can try k=1 to see if that makes it more deterministic and could reduce bias. But other params make the token distribution small. What settings do you recommend to make it as deterministic as possible? I can rerun the benchmark to see if that reduces the bias.

**Comment by turboderp** [comment]
`top_k = 1` will give you the most deterministic result, but it's not going to be 100% deterministic due to CUDA. ExLlama's kernels are inherently nondeterministic in places due to the FP16 math and the use of atomic operations, but even without that, factors like batch size and hardware configuration are also going to change the dynamics of inference. 

Basically determinism is a red herring. But that doesn't mean you should be getting *significantly* worse results with paging, and the bias shouldn't be towards consistently better or worse results either way.

Looking at the two pieces of code, though:

```python
        input_ids = tokenizer.encode(prompt, add_bos=True)
        job = ExLlamaV2DynamicJobAsync(
            generator,
            input_ids=input_ids,
            max_new_tokens=self.max_tokens,
            token_healing=True,
            stop_conditions=stop_token_ids,
            gen_settings=self.settings,
        )
```

```python
            response = utils.llm_inference_generator.generate(prompt = prompt,
                                                              max_new_tokens = 2048,
                                                              add_bos = True,
                                                              stop_conditions = utils.STOP_TOKEN_IDS,
                                                              gen_settings = self.settings)
```

First of all simply calling the `generate` function doesn't disable paging. All that function does is create a job, then iterates through it, collecting the results. It should accomplish the same thing you're doing in your loop. The async wrapper just factors it a little differently to present the job as an iterator, but all the underlying interactions with the generator should be the same, and it will use paging either way unless it's explicitly disabled when the generator is created.

One difference I'm noticing is the use of token healing in one instance, though. Token healing works by removing and regenerating the last token from the input. This is generally "smart" and wouldn't be expected to produce worse outputs, but there could be something about it that's broken, maybe? It definitely changes the parameters of the test slightly, either way.

**Comment by rjmehta1993** [comment]
Thanks for that brief explanation. It does make sense.
