### ISSUE TITLE
An issue with gemma2-27b-it related to measurement

### ISSUE THREAD

**Issue by antonovkz** [turboderp/exllamav2#681]
### OS

Windows

### GPU Library

CUDA 12.x

### Python version

3.11

### Pytorch version

2.4.1+cu121

### Model

google/gemma-2-27b-it

### Describe the bug

starting approximately from model.layers.17, accuracy inevitably drops. Additionally, anis with convert.py behaves strangely.

| Measured: model.layers.16 (Attention)
 ...
 -- 6.0693 bpw  accuracy: 0.99055803
 -- 6.2842 bpw  accuracy: 0.99066629
 -- 6.8490 bpw  accuracy: 0.99091649
 -- 8.0342 bpw  accuracy: 0.99167752

| Measured: model.layers.17 (Attention)        |
 ...
 -- 6.0693 bpw  accuracy: 0.98350188
 -- 6.2842 bpw  accuracy: 0.98359595
 -- 6.8490 bpw  accuracy: 0.98385361
 -- 8.0342 bpw  accuracy: 0.98456962

| Measured: model.layers.44 (Attention)        |
 ...
 -- 6.0693 bpw  accuracy: 0.95537142
 -- 6.2842 bpw  accuracy: 0.95538430
 -- 6.8490 bpw  accuracy: 0.95539893
 -- 8.0342 bpw  accuracy: 0.95542682
….

| Measured: model.layers.45 (Attention)  
...
 -- 6.0693 bpw  accuracy: 0.65212985
 -- 6.2842 bpw  accuracy: 0.65213043
 -- 6.8490 bpw  accuracy: 0.65213116
 -- 8.0342 bpw  accuracy: 0.65213239
 
 ...
 -- Quantization strategy:
 --   model.layers.0.self_attn                           4.1927 bpw - exp. error: 0.01036710
 --   model.layers.0.mlp                                 6.2842 bpw - exp. error: 0.00314476
 --   model.layers.1.self_attn                           3.1625 bpw - exp. error: 0.00274424
 --   model.layers.1.mlp                                 6.0693 bpw - exp. error: 0.00089989
 --   model.layers.2.self_attn                           4.1927 bpw - exp. error: 0.00155978
 --   model.layers.2.mlp                                 3.6168 bpw - exp. error: 0.00529545
 --   model.layers.3.self_attn                           4.1927 bpw - exp. error: 0.00152611
 --   model.layers.3.mlp                                 4.1342 bpw - exp. error: 0.00426974
 --   model.layers.4.self_attn                           4.0833 bpw - exp. error: 0.00204384
 --   model.layers.4.mlp                                 8.0342 bpw - exp. error: 0.00031547
 --   model.layers.5.self_attn                           4.3315 bpw - exp. error: 0.00259857
 --   model.layers.5.mlp                                 5.3300 bpw - exp. error: 0.00160373
 --   model.layers.6.self_attn                           4.1356 bpw - exp. error: 0.00279838
 --   model.layers.6.mlp                                 3.6168 bpw - exp. error: 0.00597132
 --   model.layers.7.self_attn                           4.3315 bpw - exp. error: 0.00299906
 --   model.layers.7.mlp                                 6.8490 bpw - exp. error: 0.00074052
 --   model.layers.8.self_attn                           4.1625 bpw - exp. error: 0.00264753
 --   model.layers.8.mlp                                 6.8490 bpw - exp. error: 0.00099410
 --   model.layers.9.self_attn                           5.3882 bpw - exp. error: 0.00188760
 --   model.layers.9.mlp                                 4.1342 bpw - exp. error: 0.00835163
 --   model.layers.10.self_attn                          4.3315 bpw - exp. error: 0.00426835
 --   model.layers.10.mlp                                4.3468 bpw - exp. error: 0.00547439
 --   model.layers.11.self_attn                          4.1356 bpw - exp. error: 0.00520465
 --   model.layers.11.mlp                                6.2842 bpw - exp. error: 0.00126248
 --   model.layers.12.self_attn                          3.1572 bpw - exp. error: 0.00948251
 --   model.layers.12.mlp                                4.3468 bpw - exp. error: 0.00433690
 --   model.layers.13.self_attn                          4.0415 bpw - exp. error: 0.00816338
 --   model.layers.13.mlp                                3.6168 bpw - exp. error: 0.00938453
 --   model.layers.14.self_attn                          5.3882 bpw - exp. error: 0.00179649
 --   model.layers.14.mlp                                4.1952 bpw - exp. error: 0.00531732
 --   model.layers.15.self_attn                          4.0467 bpw - exp. error: 0.00708939
 --   model.layers.15.mlp                                4.2568 bpw - exp. error: 0.01033737
 --   model.layers.16.self_attn                          4.0833 bpw - exp. error: 0.01022576
 --   model.layers.16.mlp                                4.3468 bpw - exp. error: 0.01251917
 --   model.layers.17.self_attn                          6.4689 bpw - exp. error: 0.00820395
 --   model.layers.17.mlp                                4.1342 bpw - exp. error: 0.02055939
 --   model.layers.18.self_attn                          5.3882 bpw - exp. error: 0.01516151
 --   model.layers.18.mlp                                6.2842 bpw - exp. error: 0.02166912
 --   model.layers.19.self_attn                          8.0415 bpw - exp. error: 0.01909572
 --   model.layers.19.mlp                                5.3300 bpw - exp. error: 0.02636936
 --   model.layers.20.self_attn                          6.4689 bpw - exp. error: 0.02425230
 --   model.layers.20.mlp                                6.2842 bpw - exp. error: 0.03072097
 --   model.layers.21.self_attn                          8.0415 bpw - exp. error: 0.02743362
 --   model.layers.21.mlp                                5.2401 bpw - exp. error: 0.03576874
 --   model.layers.22.self_attn                          8.0415 bpw - exp. error: 0.03211470
 --   model.layers.22.mlp                                6.0693 bpw - exp. error: 0.04048028
 --   model.layers.23.self_attn                          8.0415 bpw - exp. error: 0.03786832
 --   model.layers.23.mlp                                5.3300 bpw - exp. error: 0.05663950
 --   model.layers.24.self_attn                          5.3882 bpw - exp. error: 0.05390882
 --   model.layers.24.mlp                                8.0342 bpw - exp. error: 0.07436550
 --   model.layers.25.self_attn                          5.3054 bpw - exp. error: 0.07367399
 --   model.layers.25.mlp                                5.3300 bpw - exp. error: 0.09583494
 --   model.layers.26.self_attn                          6.4689 bpw - exp. error: 0.09442869
 --   model.layers.26.mlp                                5.3300 bpw - exp. error: 0.10446166
 --   model.layers.27.self_attn                          5.3054 bpw - exp. error: 0.10155631
 --   model.layers.27.mlp                                5.3300 bpw - exp. error: 0.11051381
 --   model.layers.28.self_attn                          4.1927 bpw - exp. error: 0.10769626
 --   model.layers.28.mlp                                8.0342 bpw - exp. error: 0.13791409
 --   model.layers.29.self_attn                          6.0415 bpw - exp. error: 0.13405096
 --   model.layers.29.mlp                                4.3468 bpw - exp. error: 0.15331666
 --   model.layers.30.self_attn                          5.3882 bpw - exp. error: 0.15045988
 --   model.layers.30.mlp                                6.2842 bpw - exp. error: 0.15094182
 --   model.layers.31.self_attn                          6.4689 bpw - exp. error: 0.14688177
 --   model.layers.31.mlp                                4.2568 bpw - exp. error: 0.14698010
 --   model.layers.32.self_attn                          4.0467 bpw - exp. error: 0.14262070
 --   model.layers.32.mlp                                6.0693 bpw - exp. error: 0.14237672
 --   model.layers.33.self_attn                          4.1625 bpw - exp. error: 0.14072269
 --   model.layers.33.mlp                                5.3300 bpw - exp. error: 0.15244348
 --   model.layers.34.self_attn                          5.3882 bpw - exp. error: 0.14843852
 --   model.layers.34.mlp                                5.2401 bpw - exp. error: 0.15596799
 --   model.layers.35.self_attn                          5.3882 bpw - exp. error: 0.15265263
 --   model.layers.35.mlp                                6.0693 bpw - exp. error: 0.15793686
 --   model.layers.36.self_attn                          4.1927 bpw - exp. error: 0.15565169
 --   model.layers.36.mlp                                6.8490 bpw - exp. error: 0.15396340
 --   model.layers.37.self_attn                          4.1625 bpw - exp. error: 0.15000001
 --   model.layers.37.mlp                                5.2401 bpw - exp. error: 0.14688675
 --   model.layers.38.self_attn                          8.0415 bpw - exp. error: 0.14426863
 --   model.layers.38.mlp                                6.2842 bpw - exp. error: 0.14281705
 --   model.layers.39.self_attn                          4.3882 bpw - exp. error: 0.14109018
 --   model.layers.39.mlp                                6.0693 bpw - exp. error: 0.13614757
 --   model.layers.40.self_attn                          4.1356 bpw - exp. error: 0.13244547
 --   model.layers.40.mlp                                6.8490 bpw - exp. error: 0.12465132
 --   model.layers.41.self_attn                          6.0415 bpw - exp. error: 0.12153506
 --   model.layers.41.mlp                                4.1952 bpw - exp. error: 0.11808822
 --   model.layers.42.self_attn                          8.0415 bpw - exp. error: 0.10523895
 --   model.layers.42.mlp                                6.8490 bpw - exp. error: 0.10011573
 --   model.layers.43.self_attn                          8.0415 bpw - exp. error: 0.09514974
 --   model.layers.43.mlp                                4.2568 bpw - exp. error: 0.07770073
 --   model.layers.44.self_attn                          4.3315 bpw - exp. error: 0.05194970
 --   model.layers.44.mlp                                8.0342 bpw - exp. error: 0.04457318
 --   model.layers.45.self_attn                          4.1356 bpw - exp. error: 0.07979561
 --   model.layers.45.mlp                                3.3636 bpw - exp. error: 0.34796943
 -- sum(log(err)): -338.256710
 -- max(err): 0.347969

### Reproduction steps

python convert.py -i F:\Models\gemma-2-27b-it -o working -o F:\Models\gemma-2-27b-it-exl2 -om F:\Models\gemma-2-27b-it\measurement.json -so
python convert.py -i F:\Models\gemma-2-27b-it -m F:\Models\gemma-2-27b-it\measurement.json -so -o working -cf ..\models\gemma-2-27b-it-exl2-5.5bpw-hb8 -b 5.5 -hb 8 -nr

### Expected behavior

-

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by turboderp** [comment]
I just tried this but couldn't reproduce.

Are you on the latest version of ExLlama? (There was an issue with Gemma2 when support was first added requiring some inference changes to make it work.)

Also, could you test SHA256 checksums on the weights you downloaded? It looks a bit like perhaps something went wrong with one of the .safetensors files. Here's what I've got:

```
74ca36bee640853cbdcae85119eabeb73cc0c63ab852136de8a330f2f9c33697  model-00001-of-00012.safetensors
13354bc14e0eddeb1e50bc7cce9f5219e2d1492bf8addfb8efabfa5d45de768d  model-00002-of-00012.safetensors
3a8c6ed92ec81bce871a1eb5538143c5d336a12ca592887ca37865ba2614d32c  model-00003-of-00012.safetensors
f06d4211eda8e2546c7fdb38c655a96bd146b28b382ee007be29416faa8c5e46  model-00004-of-00012.safetensors
065680559b7b99fcbf3359fbe3676eadb8cfd1999fc6670789c8d01de716ec27  model-00005-of-00012.safetensors
a7f3b81dd009049c07206c2d4479a2ab55d12ec54743f686bad36d09707affc7  model-00006-of-00012.safetensors
679fcd6c8ad0ecbac864141244edfeed7fb594887ab7216a19e53c2f0500f350  model-00007-of-00012.safetensors
2ae127df61c37cbcf1e2bed5fd3fc6eea3ec37c15f6dededa279d7bba7d83184  model-00008-of-00012.safetensors
4950140e96b75421ac5064966659e9f23a7741632ead93e4df0319b9fd6140fa  model-00009-of-00012.safetensors
5e1d04f78fc6e518c1dab8fb00691af3226868fdde6046a548f9bc93eb308322  model-00010-of-00012.safetensors
c1448b676de8e8c21a7585ed60073ecf54f448082adedc125ca33a35246b198e  model-00011-of-00012.safetensors
37632f98b340e76c1c345d1681ea05bc3c8c9267e44ab5074dd5ebccb274081f  model-00012-of-00012.safetensors
```

**Comment by turboderp** [comment]
Actually, scratch that. I mean, it would be nice to confirm your files aren't corrupt, but I was able to reproduce a drop in accuracy. It's less severe than what you're seeing but it still deviates enough from previous quants I did of gemma2. So apparently some bug has crept in. I'm investigating.

**Comment by antonovkz** [comment]
> I just tried this but couldn't reproduce.
> 
> Are you on the latest version of ExLlama? (There was an issue with Gemma2 when support was first added requiring some inference changes to make it work.)
> 
> Also, could you test SHA256 checksums on the weights you downloaded? It looks a bit like perhaps something went wrong with one of the .safetensors files. Here's what I've got:
> 
> ```
> 74ca36bee640853cbdcae85119eabeb73cc0c63ab852136de8a330f2f9c33697  model-00001-of-00012.safetensors
> 13354bc14e0eddeb1e50bc7cce9f5219e2d1492bf8addfb8efabfa5d45de768d  model-00002-of-00012.safetensors
> 3a8c6ed92ec81bce871a1eb5538143c5d336a12ca592887ca37865ba2614d32c  model-00003-of-00012.safetensors
> f06d4211eda8e2546c7fdb38c655a96bd146b28b382ee007be29416faa8c5e46  model-00004-of-00012.safetensors
> 065680559b7b99fcbf3359fbe3676eadb8cfd1999fc6670789c8d01de716ec27  model-00005-of-00012.safetensors
> a7f3b81dd009049c07206c2d4479a2ab55d12ec54743f686bad36d09707affc7  model-00006-of-00012.safetensors
> 679fcd6c8ad0ecbac864141244edfeed7fb594887ab7216a19e53c2f0500f350  model-00007-of-00012.safetensors
> 2ae127df61c37cbcf1e2bed5fd3fc6eea3ec37c15f6dededa279d7bba7d83184  model-00008-of-00012.safetensors
> 4950140e96b75421ac5064966659e9f23a7741632ead93e4df0319b9fd6140fa  model-00009-of-00012.safetensors
> 5e1d04f78fc6e518c1dab8fb00691af3226868fdde6046a548f9bc93eb308322  model-00010-of-00012.safetensors
> c1448b676de8e8c21a7585ed60073ecf54f448082adedc125ca33a35246b198e  model-00011-of-00012.safetensors
> 37632f98b340e76c1c345d1681ea05bc3c8c9267e44ab5074dd5ebccb274081f  model-00012-of-00012.safetensors
> ```

> Actually, scratch that. I mean, it would be nice to confirm your files aren't corrupt, but I was able to reproduce a drop in accuracy. It's less severe than what you're seeing but it still deviates enough from previous quants I did of gemma2. So apparently some bug has crept in. I'm investigating.

The version I am using is exllamav2-0.2.4.
I have verified the file hashes, and they are identical to yours.

user@DESKTOP-SNF6O37:/mnt/f/Models/gemma-2-27b-it$ sha256sum model-000*
74ca36bee640853cbdcae85119eabeb73cc0c63ab852136de8a330f2f9c33697  model-00001-of-00012.safetensors
13354bc14e0eddeb1e50bc7cce9f5219e2d1492bf8addfb8efabfa5d45de768d  model-00002-of-00012.safetensors
3a8c6ed92ec81bce871a1eb5538143c5d336a12ca592887ca37865ba2614d32c  model-00003-of-00012.safetensors
f06d4211eda8e2546c7fdb38c655a96bd146b28b382ee007be29416faa8c5e46  model-00004-of-00012.safetensors
065680559b7b99fcbf3359fbe3676eadb8cfd1999fc6670789c8d01de716ec27  model-00005-of-00012.safetensors
a7f3b81dd009049c07206c2d4479a2ab55d12ec54743f686bad36d09707affc7  model-00006-of-00012.safetensors
679fcd6c8ad0ecbac864141244edfeed7fb594887ab7216a19e53c2f0500f350  model-00007-of-00012.safetensors
2ae127df61c37cbcf1e2bed5fd3fc6eea3ec37c15f6dededa279d7bba7d83184  model-00008-of-00012.safetensors
4950140e96b75421ac5064966659e9f23a7741632ead93e4df0319b9fd6140fa  model-00009-of-00012.safetensors
5e1d04f78fc6e518c1dab8fb00691af3226868fdde6046a548f9bc93eb308322  model-00010-of-00012.safetensors
c1448b676de8e8c21a7585ed60073ecf54f448082adedc125ca33a35246b198e  model-00011-of-00012.safetensors
37632f98b340e76c1c345d1681ea05bc3c8c9267e44ab5074dd5ebccb274081f  model-00012-of-00012.safetensors

**Comment by turboderp** [comment]
There should be a fix now in the dev branch. It was a small oversight while fixing some other model that had an unintended side effect, but I am getting consistent results now.

**Comment by antonovkz** [comment]
> There should be a fix now in the dev branch. It was a small oversight while fixing some other model that had an unintended side effect, but I am getting consistent results now.

Yes, I checked everything on my end, and it worked perfectly. The issue is definitely resolved! Thank you, you’re the best!

```
 -- error_norm: 1.578165
 -- Quantization strategy:
 --   model.layers.0.self_attn                           6.0415 bpw - exp. error: 0.00377523
 --   model.layers.0.mlp                                 6.8490 bpw - exp. error: 0.00181946
 --   model.layers.1.self_attn                           4.3315 bpw - exp. error: 0.00130348
 --   model.layers.1.mlp                                 3.6168 bpw - exp. error: 0.00462543
 --   model.layers.2.self_attn                           5.3882 bpw - exp. error: 0.00069977
 --   model.layers.2.mlp                                 6.0693 bpw - exp. error: 0.00108139
 --   model.layers.3.self_attn                           5.3054 bpw - exp. error: 0.00078263
 --   model.layers.3.mlp                                 5.2401 bpw - exp. error: 0.00192402
 --   model.layers.4.self_attn                           4.0833 bpw - exp. error: 0.00204195
 --   model.layers.4.mlp                                 4.1342 bpw - exp. error: 0.00419045
 --   model.layers.5.self_attn                           4.3882 bpw - exp. error: 0.00235338
 --   model.layers.5.mlp                                 3.6168 bpw - exp. error: 0.00600778
 --   model.layers.6.self_attn                           6.0415 bpw - exp. error: 0.00096014
 --   model.layers.6.mlp                                 3.3636 bpw - exp. error: 0.00700403
 --   model.layers.7.self_attn                           8.0415 bpw - exp. error: 0.00032838
 --   model.layers.7.mlp                                 4.2568 bpw - exp. error: 0.00392328
 --   model.layers.8.self_attn                           4.0415 bpw - exp. error: 0.00338808
 --   model.layers.8.mlp                                 4.1342 bpw - exp. error: 0.00518325
 --   model.layers.9.self_attn                           8.0415 bpw - exp. error: 0.00047856
 --   model.layers.9.mlp                                 5.2401 bpw - exp. error: 0.00390317
 --   model.layers.10.self_attn                          4.1927 bpw - exp. error: 0.00434684
 --   model.layers.10.mlp                                5.2401 bpw - exp. error: 0.00333275
 --   model.layers.11.self_attn                          6.0415 bpw - exp. error: 0.00165707
 --   model.layers.11.mlp                                4.1952 bpw - exp. error: 0.00455330
 --   model.layers.12.self_attn                          8.0415 bpw - exp. error: 0.00038967
 --   model.layers.12.mlp                                4.3468 bpw - exp. error: 0.00435231
 --   model.layers.13.self_attn                          8.0415 bpw - exp. error: 0.00047963
 --   model.layers.13.mlp                                4.1952 bpw - exp. error: 0.00512339
 --   model.layers.14.self_attn                          6.0415 bpw - exp. error: 0.00162044
 --   model.layers.14.mlp                                4.1952 bpw - exp. error: 0.00533510
 --   model.layers.15.self_attn                          5.3054 bpw - exp. error: 0.00263772
 --   model.layers.15.mlp                                5.3300 bpw - exp. error: 0.00285151
 --   model.layers.16.self_attn                          5.3054 bpw - exp. error: 0.00291450
 --   model.layers.16.mlp                                6.2842 bpw - exp. error: 0.00166555
 --   model.layers.17.self_attn                          5.3882 bpw - exp. error: 0.00246371
 --   model.layers.17.mlp                                4.3468 bpw - exp. error: 0.00606814
 --   model.layers.18.self_attn                          5.3882 bpw - exp. error: 0.00248878
 --   model.layers.18.mlp                                6.0693 bpw - exp. error: 0.00201260
 --   model.layers.19.self_attn                          8.0415 bpw - exp. error: 0.00061043
 --   model.layers.19.mlp                                6.0693 bpw - exp. error: 0.00204750
 --   model.layers.20.self_attn                          6.4689 bpw - exp. error: 0.00240574
 --   model.layers.20.mlp                                5.3300 bpw - exp. error: 0.00329139
 --   model.layers.21.self_attn                          8.0415 bpw - exp. error: 0.00098940
 --   model.layers.21.mlp                                6.0693 bpw - exp. error: 0.00259313
 --   model.layers.22.self_attn                          6.0415 bpw - exp. error: 0.00523064
 --   model.layers.22.mlp                                6.2842 bpw - exp. error: 0.00246372
 --   model.layers.23.self_attn                          8.0415 bpw - exp. error: 0.00183437
 --   model.layers.23.mlp                                5.3300 bpw - exp. error: 0.00410316
 --   model.layers.24.self_attn                          8.0415 bpw - exp. error: 0.00185904
 --   model.layers.24.mlp                                6.0693 bpw - exp. error: 0.00281867
 --   model.layers.25.self_attn                          8.0415 bpw - exp. error: 0.00173566
 --   model.layers.25.mlp                                6.0693 bpw - exp. error: 0.00248638
 --   model.layers.26.self_attn                          6.4689 bpw - exp. error: 0.00211894
 --   model.layers.26.mlp                                6.0693 bpw - exp. error: 0.00257129
 --   model.layers.27.self_attn                          8.0415 bpw - exp. error: 0.00084772
 --   model.layers.27.mlp                                6.0693 bpw - exp. error: 0.00244090
 --   model.layers.28.self_attn                          8.0415 bpw - exp. error: 0.00070139
 --   model.layers.28.mlp                                5.3300 bpw - exp. error: 0.00401164
 --   model.layers.29.self_attn                          5.3054 bpw - exp. error: 0.00337516
 --   model.layers.29.mlp                                6.0693 bpw - exp. error: 0.00265097
 --   model.layers.30.self_attn                          8.0415 bpw - exp. error: 0.00092899
 --   model.layers.30.mlp                                5.3300 bpw - exp. error: 0.00361495
 --   model.layers.31.self_attn                          5.3882 bpw - exp. error: 0.00233766
 --   model.layers.31.mlp                                6.8490 bpw - exp. error: 0.00185042
 --   model.layers.32.self_attn                          4.1625 bpw - exp. error: 0.00392116
 --   model.layers.32.mlp                                6.8490 bpw - exp. error: 0.00181972
 --   model.layers.33.self_attn                          8.0415 bpw - exp. error: 0.00066285
 --   model.layers.33.mlp                                6.2842 bpw - exp. error: 0.00217789
 --   model.layers.34.self_attn                          5.3882 bpw - exp. error: 0.00220323
 --   model.layers.34.mlp                                6.0693 bpw - exp. error: 0.00247529
 --   model.layers.35.self_attn                          5.3882 bpw - exp. error: 0.00218450
 --   model.layers.35.mlp                                6.8490 bpw - exp. error: 0.00195283
 --   model.layers.36.self_attn                          5.3882 bpw - exp. error: 0.00301109
 --   model.layers.36.mlp                                6.0693 bpw - exp. error: 0.00240417
 --   model.layers.37.self_attn                          5.3054 bpw - exp. error: 0.00423544
 --   model.layers.37.mlp                                6.0693 bpw - exp. error: 0.00237848
 --   model.layers.38.self_attn                          6.4689 bpw - exp. error: 0.00144064
 --   model.layers.38.mlp                                5.3300 bpw - exp. error: 0.00344082
 --   model.layers.39.self_attn                          6.4689 bpw - exp. error: 0.00182166
 --   model.layers.39.mlp                                5.3300 bpw - exp. error: 0.00338045
 --   model.layers.40.self_attn                          8.0415 bpw - exp. error: 0.00089607
 --   model.layers.40.mlp                                6.0693 bpw - exp. error: 0.00240303
 --   model.layers.41.self_attn                          6.4689 bpw - exp. error: 0.00240707
 --   model.layers.41.mlp                                5.2401 bpw - exp. error: 0.00393780
 --   model.layers.42.self_attn                          6.4689 bpw - exp. error: 0.00223835
 --   model.layers.42.mlp                                5.2401 bpw - exp. error: 0.00504500
 --   model.layers.43.self_attn                          6.4689 bpw - exp. error: 0.00259140
 --   model.layers.43.mlp                                5.3300 bpw - exp. error: 0.00393762
 --   model.layers.44.self_attn                          8.0415 bpw - exp. error: 0.00092061
 --   model.layers.44.mlp                                5.3300 bpw - exp. error: 0.00306531
 --   model.layers.45.self_attn                          6.0415 bpw - exp. error: 0.00125493
 --   model.layers.45.mlp                                4.1952 bpw - exp. error: 0.00388281
 -- sum(log(err)): -562.198870
 -- max(err): 0.007004
 -- Tokenizing samples...
```
