### ISSUE TITLE
Fedora 41 support?

### ISSUE THREAD

**Issue by frenzybiscuit** [turboderp/exllamav2#698]
### Problem

Is fedora 41 supported?

I am trying to install this in a python 3.11 venv with cuda 12.6 downloaded from nvidia's website and the environmental vars setup in /etc/environment & .bashrc for cuda, but I keep running into errors during the build process.

Llamacpp build works (outside of python venv) as does ollama, though, so its something to do with exllamav2 or the package versions in fedora 41.

### Solution

a possible solution.

### Explanation

a possible solution.

### Acknowledgements

- [X] I have looked for similar requests before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will make my requests politely.

**Comment by turboderp** [comment]
Fedora is supported, and I have no idea why it would fail to compile on your system. I'd need a bit more information, like an error message from the compiler or, well, anything really. There is nothing to go on here.

Also keep in mind, if you install one of the prebuilt wheels you won't need CUDA Toolkit and the other build reqs installed.

**Comment by DocShotgun** [comment]
TabbyAPI uses a prebuilt wheel and thus bypasses the need to compile locally.
