### ISSUE TITLE
[BUG] Formatron is not working with DynamicJob

### ISSUE THREAD

**Issue by abpani** [turboderp/exllamav2#699]
### OS

Linux

### GPU Library

CUDA 12.x

### Python version

3.10

### Pytorch version

2.4.1

### Describe the bug

job = ExLlamaV2DynamicJob(
                        input_ids = [ids],
                        filters = [[filters]],
                        max_new_tokens = self.max_tokens,
                        token_healing = True,
                        stop_conditions = utils.stop_conditions,
                        gen_settings = self.settings,
                    )
                    
tried giving input_ids as 
ids or [ids]
in both scenarios it gives the error as 
'list' object has no attribute 'background_drop'

it happens when we give the prompt as a string in dynamic generator and pass a filter

### Reproduction steps

filters = create_formatter_filter(model, tokenizer, formatter)

job = ExLlamaV2DynamicJob(
                        input_ids = [ids],
                        filters = [[filters]],
                        max_new_tokens = self.max_tokens,
                        token_healing = True,
                        stop_conditions = utils.stop_conditions,
                        gen_settings = self.settings,
                    )

### Expected behavior

Formatrong should work with DynamiJob too.

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by DocShotgun** [comment]
https://github.com/turboderp/exllamav2/commit/f4119aec5bf4fe5252b6f936d9d52e226ddb9381

**Comment by abpani** [comment]
lol just changing to this it worked 
[[filters]] - > [filters]
