### ISSUE TITLE
Can we run a 34B model with just 12gb Vram

### ISSUE THREAD

**Issue by Gyro0o** [turboderp/exllamav2#7]
- Since it was able to run Llama2 70B on a single 24 GB GPU with a 2048-token context, 
- Is there a chance you could run something like codellama 34b with 12gb vram?

**Comment by turboderp** [comment]
It would be another very tight fit, not leaving much room for context. Then again with GQA it might just work. But it remains to be seen how useful these aggressive quants are in practice, or if you're not maybe better served running the 13B version at a somewhat higher bitrate.

**Comment by Xavi007** [comment]
I agree with turboderp that running Codellama 34B on a single 12GB VRAM GPU will be a tight fit. It is possible that it will work with GQA, but it is important to be aware of the potential performance impact.

I would also recommend considering running the 13B version of Codellama at a somewhat higher bitrate. This will allow you to use a larger context size and get better performance.

Ultimately, the best way to decide whether to run Codellama 34B or the 13B version is to experiment with both and see which one works better for your specific needs.

**Comment by epicfilemcnulty** [comment]
@Gyro0o I've converted Phind-Codellama-34B, you can try this quant: https://huggingface.co/latimar/Phind-Codellama-34B-v2-exl2/tree/2_55-bpw-h6

but it's still 11.3GB, so I have doubts if it fits...I'll create and upload a 2.4 bpw quant of this model too.
