### ISSUE TITLE
[BUG] 1.0 bpw not possible?

### ISSUE THREAD

**Issue by frenzybiscuit** [turboderp/exllamav2#700]
### OS

Linux

### GPU Library

CUDA 12.x

### Python version

3.11

### Pytorch version

N/A

### Model

https://huggingface.co/FrenzyBiscuit/Skyfall-39B-v1-1.0bpw-h6-exl2

### Describe the bug

I just did a 1.0 bpw conversion, but the size ended up being the exact same as the 2.0bpw.

Is it not possible to do a 1.0bpw quant?

### Reproduction steps

CUDA_VISIBLE_DEVICES=1 python3 convert.py -i ~/weights/Skyfall-39B-v1 -o ~/mytemp2 -m measurement.json -cf ~/Skyfall-39B-v1-1.0bpw-h6-exl2 -b 1.0 -hb 6

### Expected behavior

works

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by DocShotgun** [comment]
No, it's not possible.

https://github.com/turboderp/exllamav2/issues/675#issuecomment-2483119609
