### ISSUE TITLE
[BUG] RoPE Scaling through Alpha

### ISSUE THREAD

**Issue by Vhallo** [turboderp/exllamav2#704]
### OS

Windows

### GPU Library

CUDA 12.x

### Python version

3.12

### Pytorch version

2.5.1

### Describe the bug

I encountered a strange issue, which starts with 0.2.5 (also in 0.2.6):

RoPE scaling through Alpha values doesn't seem to get applied anymore, and the model goes insane after the context limit is reached. Reverting back to 0.2.4 immediately fixes the issue. Alternatively, directly setting the correct Theta in the model config.json works too, which is why I only noticed this now. 

### Reproduction steps

Using tabbyAPI + LLama 3, try to apply RoPE scaling through Alpha.

### Expected behavior

It just works. ™

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by turboderp** [comment]
Thanks, it looks like the alpha value wasn't being carried over after refactoring to support some other RoPE flavors. Should be fixed in dev now.

**Comment by Vhallo** [comment]
Good to hear you found the issue!
