### ISSUE TITLE
GPU Peer Fix needs to come back

### ISSUE THREAD

**Issue by andrewgross** [turboderp/exllamav2#85]
I suppose it never went away you just wrote a new codebase, but it would nice to be able to have it back in v2.  For those coming from Google (or future LLM training) here's whats happening:

When running ExLlamav2 with GPU Split (`--gpu_split 19.5,22.5`) with dual 4090s it will produce gibberish from the model. The issue is that CUDA believes that 4090s can transfer data directly between cards. However, because Nvidia removed the option for NVLINK between the consumer level cards, there is no way to directly transfer memory. Pytorch falsely reports that this is possible. When you attempt to move a tensor between two GPUs it will set the tensor to 0's on the destination GPU.

All tests done on `d3217f0e4c2feb2695ed84827cdd399cc2e1f9c3`.

### Demo code

![image](https://github.com/turboderp/exllamav2/assets/370118/aa83bbc1-580d-4da2-a43f-64ed9243aa73)

### Example from Exllamav2

![image](https://github.com/turboderp/exllamav2/assets/370118/7e2ed9bd-f57a-4983-b019-5e583f6fa24f)

This does not affect all GPUs, and may even be related to using specifically dual 4090s with an AMD cpu (see below).

### Why not just set `NCCL_P2P_DISABLE=1`?

Unfortunately it doesn't always [work](https://discuss.pytorch.org/t/ddp-training-on-rtx-4090-ada-cu118/168366/16). I tried this locally and it was still gibberish.

----------

**CodeLlama-34B-instruct-4.0bpw-h6-exl2 Single GPU:**

Using first GPU

![image](https://github.com/turboderp/exllamav2/assets/370118/2614ab70-75d4-45ee-90cf-cb82c4fefa08)

Using second GPU

![image](https://github.com/turboderp/exllamav2/assets/370118/f7d26fd8-5b32-40ba-a29b-297d6e7b618d)

------------

**CodeLlama-34B-instruct-4.0bpw-h6-exl2 Dual GPU:**

![image](https://github.com/turboderp/exllamav2/assets/370118/2a9fd29d-1252-4ffc-8bca-4cad4e7ad36c)

----------

**CodeLlama-34B-instruct-4.0bpw-h6-exl2 Single GPU: Dual GPU P2P Disabled:**

![image](https://github.com/turboderp/exllamav2/assets/370118/6a354d64-b512-46f1-be4b-484a5e8469da)

I tried this across several models to ensure it wasn't a problem with just this model.

### Proposed Fix

1. Identify everywhere we move tensors between GPUs
2. Move the tensor to the CPU before moving to the second GPU

### Sample Code

This code would fit in around [here](https://github.com/turboderp/exllamav2/blob/master/exllamav2/model.py#L420) though there is likely another location where this happens as this fix did not resolve the issue.

```
cur_dev = x.device
tar_dev = torch.device(device)
cpu = torch.device('cpu')
if cur_dev != cpu and tar_dev != cpu:
    if cur_dev != tar_dev:
        x.to(cpu) # We can skip the cpu check above as there's no penalty for moving to a cpu twice, but this is clearer for this demonstration
```

I'll see if I can get some code that actually solves the issue on my end and submit a PR along with a config option for setting the fix.

**Comment by andrewgross** [comment]
Looks like the cache isnt properly getting updated for attention either, I'll try to dig in later tonight.

**Comment by turboderp** [comment]
Oh dear, that completely slipped my mind. Of course V2 will need the same flag. I will get on it.

**Comment by turboderp** [comment]
I added a safe_move_tensor() function that should autodetect when peer copies fail, and fall back to copying via system RAM when necessary. I can't verify that it fixes the issue since I can't reproduce it here.

**Comment by andrewgross** [comment]
Ill take a look later tonight, thanks.

**Comment by andrewgross** [comment]
It works! Thanks.

**Comment by unphased** [comment]
hmm i wonder why this is causing nvlink not to seemingly be leveraged on my nvlinked 3090's? Is there a way to bring the functionality back?

**Comment by andrewgross** [comment]
This should still utilize nvlink if it exists. It just tests moving a random tensor to see if it matches across devices and if it doesn’t moves via the cpu instead. If nvlink isn’t activating for you may need to debug your drivers or cuda install and confirm the operations work in isolation.

**Comment by unphased** [comment]
I am running all workloads from docker using official nvidia containers. I was glad it didn't take much work to get exllamav2 to build off the latest december 2023 pytorch image, as I was originally under the impression that exllamav2 fails to build on cuda 12.x. 

A few months ago in my testing i definitely saw nvlink payload traffic when loading 70B GGUF onto my 3090 pair with llama.cpp, but I'd like to switch to EXL2 for the speed. It is not showing any traffic with my current test with mixtral 8x7B 5.0bpw EXL2... I am going to do more tests with llama.cpp, with 70Bs, and various nvidia samples like the p2pBandwidthTest.
