### ISSUE TITLE
Maximum bitrate

### ISSUE THREAD

**Issue by Grimulkan** [turboderp/exllamav2#89]
How high can we go? I need an alternative to testing in FP16 for my unquantized reference all the time. Since exllama doesn't support load_in_8_bit, I figured I'd try an 8-bit quant, but couldn't get measurement.json to complete (I set head_bits to 8 also).

Is there a theoretical maximum, due to numerical issues, etc? Anyone completed a higher bit-rate quantization?

**Comment by turboderp** [comment]
The theoretical maximum is about 8.13, though I'm actually not sure if it will break if you try mode than 8.12. 8.0 should be easily achievable, though, I've made a bunch of quants like that.

The measurement.json file is created with no regard to the target bitrate. It's the full measurement on the entire model for each possible setting for each layer. The target bitrate is only applied afterwards in the optimization step.

**Comment by Grimulkan** [comment]
I see - so I can re-use the measurement.json from an earlier quant on the same model, even if I only ended up using 4 bits, for example? Meaning calibration always sweeps up to 8.12 or so?

That tells me something else must've failed when I re-did it, because I did complete a measurement.json on that same model on an earlier commit. Will retry with that.

**Comment by turboderp** [comment]
Yes, you only need to do the measurement once per model, then you can reuse the same file to quantize to multiple different bitrates.
