### ISSUE TITLE
Dimensions overflow bug

### ISSUE THREAD

**Issue by grimulkan** [turboderp/exllamav2#90]
I think I found the issue that was my problem for both https://github.com/turboderp/exllamav2/issues/89 and https://github.com/turboderp/exllamav2/issues/44:

The `hidden_state` computed below should initially be a tensor of shape `dataset_rows x length/measurement_length x 8192` for the 70B model, but when trying to save in `quantize.py`:
```
# Get initial token embeddings

def embeddings(job, save_fn, model, measure = False):

    module = model.modules[0]
    assert isinstance(module, ExLlamaV2Embedding)

    with safe_open(job["cal_filename"], framework = "pt", device = "cpu") as f:
        input_ids = f.get_tensor("input_ids")

    module.load()
    hidden_state = module.forward(input_ids)
    module.unload()

    embeddings_dict = { "hidden_state": hidden_state }
    save_file(embeddings_dict, os.path.join(job["out_dir"], "input_states.safetensors"))
```
it can crash when saving the safetensors, because the total number of elements exceeds the size of a signed 32-bit int.

Egs, even using the Llama2 base context size = 4096 and the default 100 rows = 3,355,443,200 elements, which rolls over to a negative number when saving.

I'm not sure what the workaround should be: reducing the number of rows works, but won't that affect the quality of the quant? Could also lower the context size (length), but not sure if that affects the quant quality either.
EDIT: Could also use a longer context & fewer rows when generating measurement.json, but a shorter context and more rows when quantizing?

**Comment by turboderp** [comment]
Personally I just stick with 2048 tokens x 100 rows, even on 4k models like Llama2. It just doesn't make a measurable difference in my experience.

But, I am a little surprised if `safetensors` can't handle tensors larger than 2 GB. It's written in Rust, and it doesn't make a lot of sense to use a signed 32-bit int as a size type. Still, I'll experiment in a little bit to see, possibly report the bug upstream. 2 GB isn't huge in ML applications where `safetensors` is applied so it's definitely something they should be made aware of.

The best temporary workaround is probably just to split the hidden state into multiple tensors when saving the checkpoint.

**Comment by Grimulkan** [comment]
Thanks.

Why does hidden state need to be saved at all vs holding it in RAM? It's re-generated on every quant, right?

Also, does the context length/measurement length have to be the same between calibration & quantization? It almost seems like we could use totally different settings in measurement.json (rows, length, dataset) vs quantization.

> It just doesn't make a measurable difference in my experience.

Mine too. Probably the most sensible thing to do without a code change.

**Comment by turboderp** [comment]
>Why does hidden state need to be saved at all vs holding it in RAM? It's re-generated on every quant, right?

The hidden state is propagated through the model over the whole quantization. It's essentially doing full-precision inference on a very large batch, then using the intermediate states to calibrate. The state is saved to disk so the process can resume from the last checkpoint if it was interrupted for whatever reason.

>Also, does the context length/measurement length have to be the same between calibration & quantization?

Not really, no. The measurement isn't the calibration, it's just a measurement of how the possible quant settings make the hidden state deviate from what it would have been with the full-precision model. This is all reduced to a single number, so it's unlikely to change all that much with more test data. Which is why by default it only uses 16 rows to measure, and 100 for the actual calibration.

**Comment by Grimulkan** [comment]
> The hidden state is propagated through the model over the whole quantization. It's essentially doing full-precision inference on a very large batch, then using the intermediate states to calibrate. The state is saved to disk so the process can resume from the last checkpoint if it was interrupted for whatever reason.

As a workaround, if I comment out the input_states.safetensor save, quantization should run fine even if the hidden state exceeds 2GB? Apart from resuming that is.

> Not really, no. The measurement isn't the calibration, it's just a measurement of how the possible quant settings make the hidden state deviate from what it would have been with the full-precision model.

Gotcha. Sorry for confusing the terminology.
