### ISSUE TITLE
Feature Request: support for exllamav2 lora training

### ISSUE THREAD

**Issue by LZY-the-boys** [turboderp/exllamav2#96]
Thanks for the awesome work ! I am wondering that if possible to add lora training feature

**Comment by jgbrblmd** [comment]
since LoftQ, training lora adaptor need to initialize lora weights using delta weights: W(original) - W(quanted).
Thanks.

**Comment by turboderp** [comment]
LoRA training requires backprop, and there are no plans to implement that just yet. You can train LoRAs on other quantized formats and then use those LoRAs in ExLlama. There are some more LoRA features planned but probably not training.
